
/*
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see <http://www.gnu.org/licenses/>.
 *
 * Author: Nelson Chung
 * Creation Date: September 3, 2023
 */

class Junior_High_School_Word {
	final int id;
	final String english;
	final String chinese;
	final String phrase;
	final String sentence;

	Junior_High_School_Word({required this.id, required this.english, required this.chinese,
							 required this.phrase, required this.sentence});
}

List<Junior_High_School_Word> unit1 = [
Junior_High_School_Word(id: 1, english: "arm ", chinese: "手臂", phrase: "armpit腋下", sentence: "My brother carried a book under his arm."),
Junior_High_School_Word(id: 2, english: "back", chinese: "背部, 背面, 退後", phrase: "behind sb’s back背地裡;to knowsb/sth like the back of sb’s hand對…嘹若指掌", sentence: "She always talks about me behind my back."),
Junior_High_School_Word(id: 3, english: "Bite", chinese: "咬", phrase: "bite off more than one can chew咬得比嘴大", sentence: "Be careful, that dog might bite."),
Junior_High_School_Word(id: 4, english: "blow", chinese: "吹氣", phrase: "blow off steam發洩情緒", sentence: "The wind blew the leaves away."),
Junior_High_School_Word(id: 5, english: "body", chinese: "身體", phrase: "body language身體語言", sentence: "She has a strong body."),
Junior_High_School_Word(id: 6, english: "bottom", chinese: "臀部, 底部", phrase: "from the bottom of sb’s heart衷心的", sentence: "The letter was hidden at the bottom of the drawer."),
Junior_High_School_Word(id: 7, english: "bow", chinese: "鞠躬彎腰", phrase: "bow down to向...鞠躬", sentence: "He took a bow after his performance."),
Junior_High_School_Word(id: 8, english: "carry", chinese: "提, 運載", phrase: "carrier運送工具", sentence: "She carried the bag on her shoulder."),
Junior_High_School_Word(id: 9, english: "catch", chinese: "接住, 趕上, 染上", phrase: "catch one's eye引人注目", sentence: "I will catch the next bus."),
Junior_High_School_Word(id: 10, english: "clap", chinese: "拍手", phrase: "clap along隨著節奏拍手", sentence: "The audience clapped loudly."),
Junior_High_School_Word(id: 11, english: "cry", chinese: "哭泣", phrase: "cry over spilled milk後悔", sentence: "She started to cry when she lost her toy."),
Junior_High_School_Word(id: 12, english: "drop", chinese: "摔, 丟下", phrase: "drop by順道拜訪", sentence: "He dropped his phone and the screen cracked."),
Junior_High_School_Word(id: 13, english: "ear", chinese: "耳朵, 聽力, 音感", phrase: "all ears洗耳恭聽", sentence: "She whispered a secret into my ear."),
Junior_High_School_Word(id: 14, english: "eye", chinese: "眼睛, 視力, ]眼光", phrase: "keep an eye on留意", sentence: "She has beautiful blue eyes."),
Junior_High_School_Word(id: 15, english: "face", chinese: "臉, 面對", phrase: "to put on/pull a long face板起臉來;to lose face丟臉/to face the music面對現實", sentence: "When she heard the news, she bravely faced the situation."),
Junior_High_School_Word(id: 16, english: "fall", chinese: "跌倒", phrase: "fall apart破碎", sentence: "Be careful not to fall on the slippery floor."),
Junior_High_School_Word(id: 17, english: "finger", chinese: "手指", phrase: "", sentence: "She wore a ring on her index finger."),
Junior_High_School_Word(id: 18, english: "follow", chinese: "跟隨, 在…之後", phrase: "", sentence: "I'll follow you wherever you go."),
Junior_High_School_Word(id: 19, english: "foot", chinese: "腳", phrase: "", sentence: "She hurt her foot while hiking."),
Junior_High_School_Word(id: 20, english: "hair", chinese: "頭髮", phrase: "straight hair直髮curly hair捲髮", sentence: "She brushed her long, straight hair every morning."),
Junior_High_School_Word(id: 21, english: "hand", chinese: "手, 交給", phrase: "to give sb a hand幫某人忙;to give sb a big hand為某人鼓掌", sentence: "He handed the book to her with a smile."),
Junior_High_School_Word(id: 22, english: "head", chinese: "頭部, 頭腦", phrase: "head over heels深深地", sentence: "He scratched his head in confusion."),
Junior_High_School_Word(id: 24, english: "hit", chinese: "打, 碰撞", phrase: "hit the road上路", sentence: "He hit the ball with the bat."),
Junior_High_School_Word(id: 25, english: "hold", chinese: "抓住, 舉辦", phrase: "hold on等一下", sentence: "Can you hold this for me?"),
Junior_High_School_Word(id: 26, english: "hop", chinese: "單腳跳", phrase: "Hip hop嘻哈音樂", sentence: "The children love to hop around the playground."),
Junior_High_School_Word(id: 27, english: "jump", chinese: "跳過", phrase: "jump to conclusions草率判斷", sentence: "The cat jumped over the fence."),
Junior_High_School_Word(id: 28, english: "kick", chinese: "踢", phrase: "kick off開始", sentence: "He kicked the ball into the goal."),
Junior_High_School_Word(id: 29, english: "kiss", chinese: "親吻", phrase: "kiss goodbye告別", sentence: "She gave her grandmother a kiss on the cheek."),
Junior_High_School_Word(id: 30, english: "knee", chinese: "膝蓋", phrase: "knee-deep深達膝蓋", sentence: "He hurt his knee while playing soccer."),
Junior_High_School_Word(id: 31, english: "knock", chinese: "敲", phrase: "knock on wood敲木頭以求好運", sentence: "Someone knocked on the door."),
Junior_High_School_Word(id: 32, english: "laugh", chinese: "笑聲, 發笑", phrase: "to laugh at sb嘲笑 ", sentence: "Her laugh is so contagious that it makes everyone else laugh too."),
Junior_High_School_Word(id: 33, english: "leg", chinese: "腿", phrase: "To pull sb’s leg開某人玩笑", sentence: "She has long legs that make her look taller."),
Junior_High_School_Word(id: 34, english: "lie", chinese: "躺, 欺騙", phrase: "white lie善意的謊言", sentence: "She lies on the bed when she's tired."),
Junior_High_School_Word(id: 35, english: "lip", chinese: "嘴唇", phrase: "Lipstick口紅", sentence: "Her lips turned red from the cold."),
Junior_High_School_Word(id: 36, english: "mouth", chinese: "嘴吧", phrase: "to speak with sb’s mouth full說話時塞滿嘴吧", sentence: "Close your mouth when you chew."),
Junior_High_School_Word(id: 37, english: "move", chinese: "移動, 搬家", phrase: "make a move採取行動", sentence: "She moved to a new city last year."),
Junior_High_School_Word(id: 38, english: "nail", chinese: "指甲", phrase: "", sentence: "She painted her nails a bright red."),
Junior_High_School_Word(id: 39, english: "neck", chinese: "脖子", phrase: "neck and neck並駕齊驅", sentence: "She wore a scarf around her neck."),
Junior_High_School_Word(id: 40, english: "nod", chinese: "點頭", phrase: "to nod off打瞌睡", sentence: "He nodded in agreement to her suggestion."),
Junior_High_School_Word(id: 41, english: "nose", chinese: "鼻子, 嗅覺, 辨識能力", phrase: "nose around四處打探", sentence: "She has a sharp nose and can smell the flowers from far away."),
Junior_High_School_Word(id: 42, english: "pick", chinese: "摘, 挖", phrase: "", sentence: "She bent down to pick a flower."),
Junior_High_School_Word(id: 43, english: "point", chinese: "指著, 分數, 重點", phrase: "point out指出", sentence: "He pointed to the sky when he saw a plane."),
Junior_High_School_Word(id: 44, english: "pull", chinese: "拉, 拖", phrase: "to put off延期", sentence: "He pulled the door open with force."),
Junior_High_School_Word(id: 45, english: "push", chinese: "推, 促使", phrase: "", sentence: "She pushed the cart through the aisle."),
Junior_High_School_Word(id: 46, english: "put", chinese: "放, 擺", phrase: "", sentence: "She put the book on the table."),
Junior_High_School_Word(id: 47, english: "run", chinese: "跑, 經營", phrase: "run into偶遇", sentence: "She runs every morning to stay fit."),
Junior_High_School_Word(id: 48, english: "shake", chinese: "握手, 搖頭", phrase: "shake hands握手", sentence: "They shook hands after the meeting."),
Junior_High_School_Word(id: 49, english: "shoulder", chinese: "肩膀", phrase: "shoulderto shoulder肩並肩 ", sentence: "He carried a heavy backpack on his shoulder."),
Junior_High_School_Word(id: 50, english: "shout", chinese: "喊叫", phrase: "shout out大聲說出", sentence: "He shouted for help when he was trapped."),
Junior_High_School_Word(id: 51, english: "sight", chinese: "視力, 觀看", phrase: "", sentence: "The Eiffel Tower is a famous sight in Paris."),
Junior_High_School_Word(id: 52, english: "sign", chinese: "手勢, 信號, 簽名", phrase: "sign up報名", sentence: "She signed her name on the document."),
Junior_High_School_Word(id: 53, english: "sit", chinese: "坐", phrase: "", sentence: "Please sit down and make yourself comfortable."),
Junior_High_School_Word(id: 54, english: "sleep", chinese: "睡", phrase: "", sentence: "She needs eight hours of sleep every night."),
Junior_High_School_Word(id: 55, english: "smile", chinese: "微笑, 笑", phrase: "smile at對...微笑", sentence: "She smiled at the baby."),
Junior_High_School_Word(id: 56, english: "stand", chinese: "站立", phrase: "stand by支持", sentence: "He stood by the window and looked outside."),
Junior_High_School_Word(id: 57, english: "stomach", chinese: "胃, 肚子", phrase: "to turn sb’s stomach使某人反胃", sentence: "I have a stomach ache from eating too much."),
Junior_High_School_Word(id: 58, english: "throat", chinese: "喉嚨", phrase: "cut-throat competition激烈的競爭", sentence: "She had a sore throat and couldn't speak."),
Junior_High_School_Word(id: 59, english: "throw", chinese: "丟", phrase: "throw away丟棄", sentence: "He threw the ball to his friend."),
Junior_High_School_Word(id: 60, english: "toe", chinese: "腳趾", phrase: "", sentence: "She stubbed her toe against the table leg."),
Junior_High_School_Word(id: 61, english: "tooth", chinese: "牙齒", phrase: "", sentence: "She lost her first baby tooth when she was six."),
Junior_High_School_Word(id: 62, english: "voice", chinese: "聲音", phrase: "raise one's voice提高嗓音", sentence: "She has a beautiful singing voice."),
Junior_High_School_Word(id: 63, english: "walk", chinese: "走路", phrase: "talk a walk散步", sentence: "Every morning, he takes a walk around the park."),
Junior_High_School_Word(id: 64, english: "wave", chinese: "招手", phrase: "wave goodbye揮手告別", sentence: "She waved to her friends from the car."),
Junior_High_School_Word(id: 65, english: "ankle", chinese: "足踝", phrase: "", sentence: "She twisted her ankle while playing basketball."),
Junior_High_School_Word(id: 66, english: "beard", chinese: "鬍子", phrase: "", sentence: "He grew a beard during the winter months."),
Junior_High_School_Word(id: 67, english: "beat", chinese: "心跳聲, 打, 擊敗", phrase: "beat around the bush拐彎抹角", sentence: "His heart beat fast when he was nervous."),
Junior_High_School_Word(id: 68, english: "blood", chinese: "血", phrase: "", sentence: "Blood is essential for transporting nutrients and oxygen throughout the body."),
Junior_High_School_Word(id: 69, english: "bone", chinese: "骨頭", phrase: "", sentence: "The dog was happily chewing on a bone."),
Junior_High_School_Word(id: 70, english: "brain", chinese: "腦子, 大腦", phrase: "", sentence: "The human brain is a complex organ responsible for thought, emotions, and more."),
Junior_High_School_Word(id: 71, english: "chase", chinese: "追", phrase: "chase after追趕", sentence: "The cat chased the mouse."),
Junior_High_School_Word(id: 72, english: "flow", chinese: "流動", phrase: "go with the flow隨波逐流", sentence: "The river flows into the sea."),
Junior_High_School_Word(id: 73, english: "gesture", chinese: "手勢", phrase: "gesture of goodwill善意的表示", sentence: "He made a gesture to show he was okay."),
Junior_High_School_Word(id: 74, english: "hip", chinese: "臀部", phrase: "", sentence: "She swayed her hips to the rhythm of the music."),
Junior_High_School_Word(id: 75, english: "hug", chinese: "擁抱", phrase: "bear hug熊抱", sentence: "She gave her friend a big hug."),
Junior_High_School_Word(id: 76, english: "joint", chinese: "關節", phrase: "", sentence: "Arthritis can cause pain in the joints."),
Junior_High_School_Word(id: 77, english: "lay", chinese: "放置", phrase: "lay down放下", sentence: "She laid the book on the table."),
Junior_High_School_Word(id: 78, english: "lick", chinese: "舔", phrase: "lick one's lips舔嘴唇", sentence: "The dog licked its paw."),
Junior_High_School_Word(id: 79, english: "lift", chinese: "抬, 舉", phrase: "lift up舉起", sentence: "He lifted the box with ease."),
Junior_High_School_Word(id: 80, english: "motion", chinese: "動作, 移動", phrase: "go through the motions機械地做", sentence: "She made a motion to signal she was ready."),
Junior_High_School_Word(id: 81, english: "movement", chinese: "動作, 移動", phrase: "freedom of movement自由移動", sentence: "The movement of the dancers was graceful."),
Junior_High_School_Word(id: 82, english: "press", chinese: "按壓, 熨燙, 印刷機", phrase: "press conference新聞發布會", sentence: "She pressed the button to start the machine."),
Junior_High_School_Word(id: 83, english: "print", chinese: "指紋, 印刷", phrase: "fingerprint指紋;footprint腳印", sentence: "The detective found a clear fingerprint on the glass."),
Junior_High_School_Word(id: 84, english: "rub", chinese: "搓揉, 抓", phrase: "rub the wrong way惹惱", sentence: "She rubbed her eyes when she was tired."),
Junior_High_School_Word(id: 85, english: "sense", chinese: "感覺, 感覺到", phrase: "to make sence有道理", sentence: "I can sense that something is wrong."),
Junior_High_School_Word(id: 86, english: "skin", chinese: "皮膚, 獸皮", phrase: "skin-deep膚淺的 ", sentence: "She has very sensitive skin and has to be careful with the products she uses."),
Junior_High_School_Word(id: 87, english: "slip", chinese: "滑倒, 滑跤", phrase: "slip of the tongue口誤", sentence: "He slipped on the wet floor."),
Junior_High_School_Word(id: 88, english: "soul", chinese: "靈魂, 內涵", phrase: "heart and soul全心全意", sentence: "Music is the food for the soul."),
Junior_High_School_Word(id: 89, english: "step", chinese: "步伐, 踏", phrase: "step by step逐步", sentence: "She took a step forward."),
Junior_High_School_Word(id: 90, english: "thumb", chinese: "拇指", phrase: "", sentence: "He gave a thumbs up to show his approval."),
Junior_High_School_Word(id: 91, english: "view", chinese: "看, 觀點, 景色", phrase: "in view of考慮到", sentence: "The view from the mountain was breathtaking."),
Junior_High_School_Word(id: 92, english: "waist", chinese: "腰部", phrase: "waist-deep深達腰部", sentence: "She has a slim waist."),
Junior_High_School_Word(id: 93, english: "wrist", chinese: "手腕", phrase: "wristwatch手錶", sentence: "He wore a watch on his wrist."),
Junior_High_School_Word(id: 94, english: "yell", chinese: "大叫", phrase: "yell out大聲叫喊", sentence: "He yelled in pain when he got hurt.")
];

List<Junior_High_School_Word> unit2 = [
Junior_High_School_Word(id: 1, english: "aunt", chinese: "阿姨", phrase: "", sentence: "My aunt lives in Taipei."),
Junior_High_School_Word(id: 2, english: "born", chinese: "出生的, , 天生的", phrase: "", sentence: "She was born in 1995."),
Junior_High_School_Word(id: 3, english: "brother", chinese: "兄弟", phrase: "", sentence: "My younger brother is in high school."),
Junior_High_School_Word(id: 4, english: "cousin", chinese: "表, , 堂兄弟", phrase: "", sentence: "My cousin is the same age as me."),
Junior_High_School_Word(id: 5, english: "daughter", chinese: "女兒", phrase: "", sentence: "Their daughter is studying abroad."),
Junior_High_School_Word(id: 6, english: "family", chinese: "家庭, , 一家人", phrase: "", sentence: "We have a big family gathering every year."),
Junior_High_School_Word(id: 7, english: "father", chinese: "父親", phrase: "", sentence: "My father works in a bank."),
Junior_High_School_Word(id: 8, english: "grandfather", chinese: "祖父", phrase: "", sentence: "My grandfather loves to tell stories."),
Junior_High_School_Word(id: 9, english: "grandmother", chinese: "祖母", phrase: "", sentence: "My grandmother makes the best cookies."),
Junior_High_School_Word(id: 10, english: "grow", chinese: "成長", phrase: "", sentence: "Children grow up so fast."),
Junior_High_School_Word(id: 11, english: "husband", chinese: "丈夫", phrase: "", sentence: "Her husband is a doctor."),
Junior_High_School_Word(id: 12, english: "live", chinese: "住, , 現場直播的", phrase: "living生計", sentence: "They live in a beautiful house."),
Junior_High_School_Word(id: 13, english: "married", chinese: "已婚的", phrase: "", sentence: "They got married last year."),
Junior_High_School_Word(id: 14, english: "mother", chinese: "母親", phrase: "", sentence: "My mother is a teacher."),
Junior_High_School_Word(id: 15, english: "parent", chinese: "雙親中的一位", phrase: "", sentence: "Parents always worry about their children."),
Junior_High_School_Word(id: 16, english: "raise", chinese: "撫養, , 舉起", phrase: "", sentence: "They raised three children in that house."),
Junior_High_School_Word(id: 17, english: "sister", chinese: "姊妹", phrase: "", sentence: "My sister is studying in college."),
Junior_High_School_Word(id: 18, english: "son", chinese: "兒子", phrase: "son-in-law女婿", sentence: "Their son just started school."),
Junior_High_School_Word(id: 19, english: "uncle", chinese: "舅舅, , 叔叔", phrase: "", sentence: "My uncle is a chef."),
Junior_High_School_Word(id: 20, english: "wife", chinese: "妻子", phrase: "", sentence: "His wife is a renowned artist."),
Junior_High_School_Word(id: 21, english: "affair", chinese: "事務, , 事件", phrase: "", sentence: "The company's financial affairs are in order."),
Junior_High_School_Word(id: 22, english: "affect", chinese: "影響", phrase: "", sentence: "The weather can greatly affect our mood."),
Junior_High_School_Word(id: 23, english: "elder", chinese: "較年長的人, , 較年長的", phrase: "vs.older,elder指兩者中年紀較大的", sentence: "He is the elder of the two brothers."),
Junior_High_School_Word(id: 24, english: "generation", chinese: "世代", phrase: "generation gap代溝", sentence: "There's often a generation gap between parents and children."),
Junior_High_School_Word(id: 25, english: "granddaughter", chinese: "孫女", phrase: "", sentence: "Their granddaughter is so adorable."),
Junior_High_School_Word(id: 26, english: "grandson", chinese: "孫子", phrase: "", sentence: "Their grandson just turned one."),
Junior_High_School_Word(id: 27, english: "growth", chinese: "成長", phrase: "", sentence: "The growth of the company has been phenomenal."),
Junior_High_School_Word(id: 28, english: "marriage", chinese: "婚姻, , 婚禮", phrase: "", sentence: "Their marriage has lasted for 25 years."),
Junior_High_School_Word(id: 29, english: "marry", chinese: "結婚", phrase: "", sentence: "She will marry her college sweetheart."),
Junior_High_School_Word(id: 30, english: "member", chinese: "成員", phrase: "membership會員資格", sentence: "He is a member of the basketball team."),
Junior_High_School_Word(id: 31, english: "nephew", chinese: "姪子, , 外甥", phrase: "", sentence: "My nephew is very mischievous."),
Junior_High_School_Word(id: 32, english: "niece", chinese: "姪女, , 外甥女", phrase: "", sentence: "My niece is very talented in music."),
Junior_High_School_Word(id: 33, english: "relation", chinese: "親戚, , 關係", phrase: "bear no, , little, , some relation to與…無關", sentence: "Their relation is quite complicated."),
Junior_High_School_Word(id: 34, english: "relative", chinese: "親戚, , ", phrase: "", sentence: "We have many relatives in the countryside."),
Junior_High_School_Word(id: 35, english: "role", chinese: "角色", phrase: "", sentence: "She played the lead role in the play."),
Junior_High_School_Word(id: 36, english: "single", chinese: "單身的", phrase: "", sentence: "He has been single for a few years now."),
Junior_High_School_Word(id: 37, english: "support", chinese: "資助, , 支持", phrase: "", sentence: "She always supports her children's decisions."),
Junior_High_School_Word(id: 38, english: "tradition", chinese: "傳統", phrase: "", sentence: "It's a tradition in our family to gather for dinner every Sunday."),
Junior_High_School_Word(id: 39, english: "wedding", chinese: "婚禮", phrase: "bride新娘;bridegroom新郎;bridesmaid伴娘;best man伴郎", sentence: "The wedding ceremony was beautiful."),
Junior_High_School_Word(id: 40, english: "related", chinese: "有親戚關係的, , 有關連的", phrase: "", sentence: "They are related by blood.")
];




List<Junior_High_School_Word> unit3 = [
Junior_High_School_Word(id: 1, english: "actor", chinese: "男演員", phrase: "lead actor", sentence: "The actor received an award for his performance."),
Junior_High_School_Word(id: 2, english: "actress", chinese: "女演員", phrase: "supporting actress", sentence: "The actress played the role brilliantly."),
Junior_High_School_Word(id: 3, english: "boss", chinese: "老闆", phrase: "like a boss", sentence: "The boss gave us a day off."),
Junior_High_School_Word(id: 4, english: "business", chinese: "生意, 職責", phrase: "on business出差;none of sb's business無關某人的事", sentence: "After years of hard work, her small shop grew into a successful business empire."),
Junior_High_School_Word(id: 5, english: "businessman", chinese: "商人", phrase: "shrewd businessman", sentence: "The businessman sealed the deal."),
Junior_High_School_Word(id: 6, english: "clerk", chinese: "店員, 職員", phrase: "desk clerk", sentence: "The clerk assisted the customer."),
Junior_High_School_Word(id: 7, english: "cook", chinese: "廚師", phrase: "home cook", sentence: "The cook prepared a delicious meal."),
Junior_High_School_Word(id: 8, english: "dentist", chinese: "牙醫", phrase: "family dentist", sentence: "The dentist advised brushing twice a day."),
Junior_High_School_Word(id: 9, english: "doctor", chinese: "醫生", phrase: "family doctor", sentence: "The doctor prescribed some medicine."),
Junior_High_School_Word(id: 10, english: "drive", chinese: "司機", phrase: "taxi driver", sentence: "The driver took a shortcut."),
Junior_High_School_Word(id: 11, english: "engineer", chinese: "工程師", phrase: "software engineer", sentence: "The engineer designed the bridge."),
Junior_High_School_Word(id: 12, english: "farmer", chinese: "農夫", phrase: "dairy farmer", sentence: "The farmer harvested the crops."),
Junior_High_School_Word(id: 13, english: "fisherman", chinese: "漁夫", phrase: "commercial fisherman", sentence: "The fisherman cast his net."),
Junior_High_School_Word(id: 14, english: "interview", chinese: "面試", phrase: "job interview", sentence: "She prepared well for the interview."),
Junior_High_School_Word(id: 15, english: "job", chinese: "工作", phrase: "full-time job", sentence: "She found a new job in the city."),
Junior_High_School_Word(id: 16, english: "lawyer", chinese: "律師", phrase: "defense lawyer", sentence: "The lawyer presented the evidence."),
Junior_High_School_Word(id: 17, english: "mailman", chinese: "郵差", phrase: "local mailman", sentence: "The mailman delivers letters every morning."),
Junior_High_School_Word(id: 18, english: "meeting", chinese: "會議", phrase: "board meeting", sentence: "The meeting lasted for two hours."),
Junior_High_School_Word(id: 19, english: "nurse", chinese: "護理師", phrase: "registered nurse", sentence: "The nurse took care of the patient."),
Junior_High_School_Word(id: 20, english: "own", chinese: "擁有, 自己的", phrase: "own up to", sentence: "He owns a small shop."),
Junior_High_School_Word(id: 21, english: "police officer", chinese: "警察", phrase: "on-duty officer", sentence: "The police officer patrolled the area."),
Junior_High_School_Word(id: 22, english: "reporter", chinese: "記者", phrase: "news reporter", sentence: "The reporter covered the event."),
Junior_High_School_Word(id: 23, english: "salesman", chinese: "推銷員", phrase: "door-to-door salesman", sentence: "The salesman offered a discount."),
Junior_High_School_Word(id: 24, english: "secretary", chinese: "秘書", phrase: "executive secretary", sentence: "The secretary scheduled the meeting."),
Junior_High_School_Word(id: 25, english: "shopkeeper", chinese: "店主", phrase: "local shopkeeper", sentence: "The shopkeeper greeted the customers."),
Junior_High_School_Word(id: 26, english: "singer", chinese: "歌手", phrase: "lead singer", sentence: "The singer released a new album."),
Junior_High_School_Word(id: 27, english: "soldier", chinese: "軍人", phrase: "foot soldier", sentence: "The soldier served his country."),
Junior_High_School_Word(id: 28, english: "waiter", chinese: "男服務生", phrase: "head waiter", sentence: "The waiter took our order."),
Junior_High_School_Word(id: 29, english: "waitress", chinese: "女服務生", phrase: "head waitress", sentence: "The waitress served the drinks."),
Junior_High_School_Word(id: 30, english: "housewife", chinese: "家庭主婦", phrase: "full-time housewife", sentence: "The housewife took care of her family."),
Junior_High_School_Word(id: 31, english: "work", chinese: "工作", phrase: "hard work", sentence: "Hard work pays off."),
Junior_High_School_Word(id: 32, english: "worker", chinese: "工人", phrase: "construction worker", sentence: "The worker completed the task."),
Junior_High_School_Word(id: 33, english: "writer", chinese: "作家", phrase: "freelance writer", sentence: "The writer published a novel."),
Junior_High_School_Word(id: 34, english: "ability", chinese: "能力", phrase: "natural ability", sentence: "Her ability to sing is amazing."),
Junior_High_School_Word(id: 35, english: "adviser", chinese: "顧問", phrase: "financial adviser", sentence: "The adviser gave some recommendations."),
Junior_High_School_Word(id: 36, english: "army", chinese: "陸軍", phrase: "join the army", sentence: "He served in the army for five years."),
Junior_High_School_Word(id: 37, english: "artist", chinese: "藝術家", phrase: "visual artist", sentence: "The artist showcased his work."),
Junior_High_School_Word(id: 38, english: "assistant", chinese: "助理", phrase: "administrative assistant", sentence: "The assistant organized the files."),
Junior_High_School_Word(id: 39, english: "babysitter", chinese: "臨時保母", phrase: "night babysitter", sentence: "The babysitter took care of the kids."),
Junior_High_School_Word(id: 40, english: "banker", chinese: "銀行員", phrase: "investment banker", sentence: "The banker approved the loan."),
Junior_High_School_Word(id: 41, english: "barker", chinese: "男理髮師", phrase: "local barker", sentence: "The barker gave him a new haircut."),
Junior_High_School_Word(id: 42, english: "builder", chinese: "建築工人", phrase: "home builder", sentence: "The builder constructed the house."),
Junior_High_School_Word(id: 43, english: "career", chinese: "職業", phrase: "career path", sentence: "She is considering a career in medicine."),
Junior_High_School_Word(id: 44, english: "chairman", chinese: "系主任, 董事長", phrase: "board chairman", sentence: "The chairman led the meeting."),
Junior_High_School_Word(id: 45, english: "chief", chinese: "首長", phrase: "chief executive", sentence: "The chief made an announcement."),
Junior_High_School_Word(id: 46, english: "coach", chinese: "教練", phrase: "sports coach", sentence: "The coach trained the team."),
Junior_High_School_Word(id: 47, english: "collector", chinese: "收藏家", phrase: "art collector", sentence: "The collector bought a rare painting."),
Junior_High_School_Word(id: 48, english: "company", chinese: "公司", phrase: "parent company", sentence: "He works for a multinational company."),
Junior_High_School_Word(id: 49, english: "cowboy", chinese: "牛仔", phrase: "rodeo cowboy", sentence: "The cowboy rode the horse."),
Junior_High_School_Word(id: 50, english: "dealer", chinese: "商人", phrase: "car dealer", sentence: "The dealer offered a good price."),
Junior_High_School_Word(id: 51, english: "designer", chinese: "設計師", phrase: "fashion designer", sentence: "The designer showcased her collection."),
Junior_High_School_Word(id: 52, english: "diplomat", chinese: "外交官", phrase: "senior diplomat", sentence: "The diplomat negotiated the treaty."),
Junior_High_School_Word(id: 53, english: "director", chinese: "導演", phrase: "film director", sentence: "The director won an award."),
Junior_High_School_Word(id: 54, english: "dramatist", chinese: "劇作家", phrase: "famous dramatist", sentence: "The dramatist wrote several plays."),
Junior_High_School_Word(id: 55, english: "educator", chinese: "教育學者", phrase: "early childhood educator", sentence: "The educator shared her insights."),
Junior_High_School_Word(id: 56, english: "electrician", chinese: "電工", phrase: "licensed electrician", sentence: "The electrician fixed the wiring."),
Junior_High_School_Word(id: 57, english: "employ", chinese: "雇用", phrase: "employ tactics", sentence: "They employ over 500 people."),
Junior_High_School_Word(id: 58, english: "employee", chinese: "雇員", phrase: "full-time employee", sentence: "The employee received a bonus."),
Junior_High_School_Word(id: 59, english: "employer", chinese: "雇主", phrase: "potential employer", sentence: "The employer conducted interviews."),
Junior_High_School_Word(id: 60, english: "firm", chinese: "公司, 穩固的", phrase: "law firm", sentence: "The firm has been in business for over 50 years."),
Junior_High_School_Word(id: 61, english: "governor", chinese: "州長, 管理者", phrase: "state governor", sentence: "The governor announced new policies."),
Junior_High_School_Word(id: 62, english: "guard", chinese: "警衛, 保全", phrase: "security guard", sentence: "The guard stood at the entrance."),
Junior_High_School_Word(id: 63, english: "guide", chinese: "嚮導", phrase: "tour guide", sentence: "The guide explained the history."),
Junior_High_School_Word(id: 64, english: "hire", chinese: "租用, 雇用", phrase: "hire a car", sentence: "They decided to hire more staff."),
Junior_High_School_Word(id: 65, english: "historian", chinese: "歷史學家", phrase: "modern historian", sentence: "The historian wrote a book."),
Junior_High_School_Word(id: 66, english: "hunter", chinese: "獵人", phrase: "bounty hunter", sentence: "The hunter tracked the animal."),
Junior_High_School_Word(id: 67, english: "industry", chinese: "工業", phrase: "music industry", sentence: "The industry is evolving rapidly."),
Junior_High_School_Word(id: 68, english: "journalist", chinese: "新聞工作者", phrase: "investigative journalist", sentence: "The journalist reported the news."),
Junior_High_School_Word(id: 69, english: "judge", chinese: "評審, 法官, 判斷", phrase: "supreme court judge", sentence: "The judge delivered the verdict."),
Junior_High_School_Word(id: 70, english: "magician", chinese: "魔術師", phrase: "street magician", sentence: "The magician performed a trick."),
Junior_High_School_Word(id: 71, english: "manager", chinese: "經理", phrase: "general manager", sentence: "The manager handled the operations."),
Junior_High_School_Word(id: 72, english: "mechanic", chinese: "技工", phrase: "auto mechanic", sentence: "The mechanic fixed the car."),
Junior_High_School_Word(id: 73, english: "military", chinese: "軍隊, 軍事的", phrase: "military service", sentence: "He served in the military."),
Junior_High_School_Word(id: 74, english: "model", chinese: "模特兒", phrase: "role model", sentence: "The model walked the runway."),
Junior_High_School_Word(id: 75, english: "musician", chinese: "音樂家", phrase: "classical musician", sentence: "The musician played the violin."),
Junior_High_School_Word(id: 76, english: "occupation", chinese: "職業", phrase: "primary occupation", sentence: "His occupation is a teacher."),
Junior_High_School_Word(id: 77, english: "official", chinese: "公務員", phrase: "government official", sentence: "The official announced the news."),
Junior_High_School_Word(id: 78, english: "operator", chinese: "操作員, 接線生", phrase: "machine operator", sentence: "The operator connected the call."),
Junior_High_School_Word(id: 79, english: "owner", chinese: "所有人", phrase: "property owner", sentence: "The owner of the house sold it."),
Junior_High_School_Word(id: 80, english: "painter", chinese: "畫家", phrase: "landscape painter", sentence: "The painter created a masterpiece."),
Junior_High_School_Word(id: 81, english: "personnel", chinese: "全體員工", phrase: "HR personnel", sentence: "The personnel are well-trained."),
Junior_High_School_Word(id: 82, english: "photographer", chinese: "攝影師", phrase: "wedding photographer", sentence: "The photographer captured the moment."),
Junior_High_School_Word(id: 83, english: "physician", chinese: "內科醫生", phrase: "primary care physician", sentence: "The physician checked the patient."),
Junior_High_School_Word(id: 84, english: "physicist", chinese: "物理學家", phrase: "nuclear physicist", sentence: "The physicist conducted an experiment."),
Junior_High_School_Word(id: 85, english: "president", chinese: "總統, 董事長", phrase: "company president", sentence: "The president addressed the nation."),
Junior_High_School_Word(id: 86, english: "priest", chinese: "牧師", phrase: "parish priest", sentence: "The priest conducted the service."),
Junior_High_School_Word(id: 87, english: "printer", chinese: "印刷業者, 印表機", phrase: "laser printer", sentence: "The printer ran out of ink."),
Junior_High_School_Word(id: 88, english: "produce", chinese: "生產", phrase: "produce goods", sentence: "The factory produces electronics."),
Junior_High_School_Word(id: 89, english: "product", chinese: "品", phrase: "new product launch", sentence: "The product received good reviews."),
Junior_High_School_Word(id: 90, english: "production", chinese: "產量", phrase: "mass production", sentence: "The production increased this year."),
Junior_High_School_Word(id: 91, english: "profession", chinese: "職業", phrase: "medical profession", sentence: "He chose teaching as his profession."),
Junior_High_School_Word(id: 92, english: "profrssor", chinese: "教授", phrase: "university professor", sentence: "The professor gave a lecture."),
Junior_High_School_Word(id: 93, english: "rent", chinese: "租用, 租金", phrase: "rent agreement", sentence: "The rent is due on the first."),
Junior_High_School_Word(id: 94, english: "sailor", chinese: "航海員", phrase: "merchant sailor", sentence: "The sailor navigated the ship."),
Junior_High_School_Word(id: 95, english: "scientist", chinese: "科學家", phrase: "research scientist", sentence: "The scientist made a discovery."),
Junior_High_School_Word(id: 96, english: "servant", chinese: "雇工, 僕人", phrase: "domestic servant", sentence: "The servant cleaned the house."),
Junior_High_School_Word(id: 97, english: "serve", chinese: "供應, 為…工作", phrase: "serve the community", sentence: "She serves in the army."),
Junior_High_School_Word(id: 98, english: "trade", chinese: "交易, 商業", phrase: "trade agreement", sentence: "The trade between the two countries increased."),
Junior_High_School_Word(id: 99, english: "trader", chinese: "商人", phrase: "stock trader", sentence: "The trader made a profit."),
Junior_High_School_Word(id: 100, english: "vender", chinese: "小販", phrase: "street vendor", sentence: "The vendor sold fresh fruits."),
];

List<Junior_High_School_Word> unit4 = [
Junior_High_School_Word(id: 1, english: "cold", chinese: "感冒", phrase: "", sentence: "I caught a cold last week."),
Junior_High_School_Word(id: 2, english: "comfortable", chinese: "舒服的", phrase: "", sentence: "This chair is very comfortable."),
Junior_High_School_Word(id: 3, english: "dead", chinese: "死去的", phrase: "", sentence: "The old tree is dead."),
Junior_High_School_Word(id: 4, english: "die", chinese: "死亡", phrase: "", sentence: "Many soldiers die in wars."),
Junior_High_School_Word(id: 5, english: "fever", chinese: "發燒", phrase: "", sentence: "She has a high fever and needs to rest."),
Junior_High_School_Word(id: 6, english: "fine", chinese: "健康的", phrase: "", sentence: "I'm feeling fine today."),
Junior_High_School_Word(id: 7, english: "headache", chinese: "頭痛", phrase: "", sentence: "I have a terrible headache."),
Junior_High_School_Word(id: 8, english: "health", chinese: "健康的", phrase: "", sentence: "Good health is more valuable than gold."),
Junior_High_School_Word(id: 9, english: "healthy", chinese: "健康的", phrase: "", sentence: "Eating vegetables and fruits keeps you healthy."),
Junior_High_School_Word(id: 10, english: "hurt", chinese: "受傷的, , 傷害", phrase: "", sentence: "He hurt his leg while playing soccer."),
Junior_High_School_Word(id: 11, english: "life", chinese: "生命", phrase: "", sentence: "Life is full of ups and downs."),
Junior_High_School_Word(id: 12, english: "medicine", chinese: "藥", phrase: "", sentence: "The doctor prescribed some medicine for my cold."),
Junior_High_School_Word(id: 13, english: "sick", chinese: "生病的", phrase: "", sentence: "He's been sick for a week."),
Junior_High_School_Word(id: 14, english: "strong", chinese: "強壯的", phrase: "", sentence: "He is strong enough to lift that box."),
Junior_High_School_Word(id: 15, english: "sore throat", chinese: "喉嚨痛", phrase: "", sentence: "I have a sore throat and can't speak loudly."),
Junior_High_School_Word(id: 16, english: "strong", chinese: "強壯的", phrase: "", sentence: "She has a strong will and determination."),
Junior_High_School_Word(id: 17, english: "tired", chinese: "疲累的", phrase: "", sentence: "After the long hike, I was really tired."),
Junior_High_School_Word(id: 18, english: "weak", chinese: "虛弱的", phrase: "", sentence: "After the illness, she felt very weak."),
Junior_High_School_Word(id: 19, english: "well", chinese: "良好的, , 好地", phrase: "", sentence: "She sings very well."),
Junior_High_School_Word(id: 20, english: "AIDS", chinese: "愛滋病", phrase: "", sentence: "AIDS is a serious global health issue."),
Junior_High_School_Word(id: 21, english: "cancer", chinese: "癌症", phrase: "", sentence: "Early detection is crucial for cancer treatment."),
Junior_High_School_Word(id: 22, english: "cough", chinese: "咳嗽", phrase: "", sentence: "He has a persistent cough."),
Junior_High_School_Word(id: 23, english: "cure", chinese: "治療", phrase: "", sentence: "There's no cure for the common cold."),
Junior_High_School_Word(id: 24, english: "death", chinese: "死亡", phrase: "", sentence: "Death is a natural part of life."),
Junior_High_School_Word(id: 25, english: "dizzy", chinese: "暈眩的", phrase: "", sentence: "I felt dizzy after spinning around."),
Junior_High_School_Word(id: 26, english: "drug", chinese: "藥品", phrase: "", sentence: "The new drug has shown promising results in trials."),
Junior_High_School_Word(id: 27, english: "drugstore", chinese: "藥局", phrase: "", sentence: "I need to pick up my prescription from the drugstore."),
Junior_High_School_Word(id: 28, english: "ease", chinese: "減輕", phrase: "", sentence: "The medicine will ease your pain."),
Junior_High_School_Word(id: 29, english: "effect", chinese: "效用, , 影響", phrase: "", sentence: "The effect of the drug was immediate."),
Junior_High_School_Word(id: 30, english: "flu", chinese: "流行性感冒", phrase: "", sentence: "Many people get the flu during winter."),
Junior_High_School_Word(id: 31, english: "homesick", chinese: "想家的", phrase: "", sentence: "She felt homesick during her first month abroad."),
Junior_High_School_Word(id: 32, english: "hunger", chinese: "飢餓", phrase: "", sentence: "The hunger was unbearable after fasting for a day."),
Junior_High_School_Word(id: 33, english: "ill", chinese: "生病的", phrase: "", sentence: "He's been ill and bedridden for days."),
Junior_High_School_Word(id: 34, english: "injury", chinese: "受傷", phrase: "", sentence: "The player sustained an injury during the match."),
Junior_High_School_Word(id: 35, english: "medical", chinese: "醫療的", phrase: "", sentence: "She's pursuing a medical degree."),
Junior_High_School_Word(id: 36, english: "pain", chinese: "痛", phrase: "", sentence: "The pain in my back is unbearable."),
Junior_High_School_Word(id: 37, english: "painful", chinese: "痛苦的", phrase: "", sentence: "The recovery process was painful."),
Junior_High_School_Word(id: 38, english: "pale", chinese: "蒼白的", phrase: "", sentence: "He looked pale after hearing the news."),
Junior_High_School_Word(id: 39, english: "physical", chinese: "身體的", phrase: "", sentence: "Regular physical activity is important for health."),
Junior_High_School_Word(id: 40, english: "poison", chinese: "毒藥", phrase: "", sentence: "Rat poison should be kept away from children."),
Junior_High_School_Word(id: 41, english: "recover", chinese: "康復", phrase: "", sentence: "It took him months to recover from the surgery."),
Junior_High_School_Word(id: 42, english: "sleepy", chinese: "想睡覺的", phrase: "", sentence: "I always feel sleepy after lunch."),
Junior_High_School_Word(id: 43, english: "stomachache", chinese: "胃痛", phrase: "", sentence: "I have a stomachache after eating too much."),
Junior_High_School_Word(id: 44, english: "toothache", chinese: "牙痛", phrase: "", sentence: "I need to see a dentist because of my toothache."),
Junior_High_School_Word(id: 45, english: "treatment", chinese: "治療, , 對待", phrase: "", sentence: "The patient is undergoing treatment for cancer."),
Junior_High_School_Word(id: 46, english: "wound", chinese: "傷口, , 使受傷", phrase: "", sentence: "The wound took weeks to heal."),
];


List<Junior_High_School_Word> unit5 = [
Junior_High_School_Word(id: 1, english: "afraid", chinese: "害怕的", phrase: "to be afraid that", sentence: "I'm afraid that it might rain."),
Junior_High_School_Word(id: 2, english: "anger", chinese: "怒氣", phrase: "", sentence: "His anger was evident by the tone of his voice."),
Junior_High_School_Word(id: 3, english: "angry", chinese: "生氣的", phrase: "", sentence: "She was angry at the unfair decision."),
Junior_High_School_Word(id: 4, english: "bored", chinese: "感到無聊的", phrase: "", sentence: "I'm bored with watching TV."),
Junior_High_School_Word(id: 5, english: "boring", chinese: "令人無聊的", phrase: "", sentence: "This movie is really boring."),
Junior_High_School_Word(id: 6, english: "busy", chinese: "忙碌的", phrase: "to be busy in", sentence: "She's busy in preparing for the exam."),
Junior_High_School_Word(id: 7, english: "care", chinese: "在乎關心", phrase: "to care for", sentence: "Do you care for some tea?"),
Junior_High_School_Word(id: 8, english: "crazy", chinese: "瘋狂的", phrase: "", sentence: "He's crazy about basketball."),
Junior_High_School_Word(id: 9, english: "excited", chinese: "感到興奮的", phrase: "", sentence: "I'm so excited about the trip."),
Junior_High_School_Word(id: 10, english: "exciting", chinese: "令人興奮的", phrase: "", sentence: "The roller coaster ride was really exciting."),
Junior_High_School_Word(id: 11, english: "glad", chinese: "高興的", phrase: "", sentence: "I'm glad to see you."),
Junior_High_School_Word(id: 12, english: "happy", chinese: "快樂的", phrase: "", sentence: "She looks happy today."),
Junior_High_School_Word(id: 13, english: "interested", chinese: "感到興趣的", phrase: "", sentence: "I'm interested in learning Spanish."),
Junior_High_School_Word(id: 14, english: "interesting", chinese: "有趣的", phrase: "", sentence: "This book is very interesting."),
Junior_High_School_Word(id: 15, english: "joy", chinese: "喜悅", phrase: "", sentence: "The news brought great joy to the family."),
Junior_High_School_Word(id: 16, english: "lonely", chinese: "孤單的", phrase: "", sentence: "He felt lonely in the big city."),
Junior_High_School_Word(id: 17, english: "mad", chinese: "生氣的", phrase: "", sentence: "Why are you mad at me?"),
Junior_High_School_Word(id: 18, english: "please", chinese: "取悅", phrase: "", sentence: "This song always pleases the audience."),
Junior_High_School_Word(id: 19, english: "surprise", chinese: "驚喜, , 使驚訝", phrase: "", sentence: "The news took everyone by surprise."),
Junior_High_School_Word(id: 20, english: "surprised", chinese: "感到驚訝的", phrase: "", sentence: "I was surprised to see him here."),
Junior_High_School_Word(id: 21, english: "terrible", chinese: "糟糕的", phrase: "", sentence: "The weather is terrible today."),
Junior_High_School_Word(id: 22, english: "unhappy", chinese: "不快樂的", phrase: "", sentence: "She seemed unhappy about the results."),
Junior_High_School_Word(id: 23, english: "worry", chinese: "擔憂, , 擔憂的事", phrase: "", sentence: "Don't worry, everything will be fine."),
Junior_High_School_Word(id: 24, english: "burst", chinese: "突然出聲, , 爆裂", phrase: "", sentence: "The balloon burst with a loud bang."),
Junior_High_School_Word(id: 25, english: "calm", chinese: "鎮靜的, , 平靜下來", phrase: "", sentence: "Calm down, it's not the end of the world."),
Junior_High_School_Word(id: 26, english: "complain", chinese: "抱怨", phrase: "complaint", sentence: "She always complains about the weather."),
Junior_High_School_Word(id: 27, english: "concern", chinese: "擔心", phrase: "", sentence: "His health is a major concern."),
Junior_High_School_Word(id: 28, english: "confuse", chinese: "使困擾", phrase: "", sentence: "The new system confuses many users."),
Junior_High_School_Word(id: 29, english: "cruel", chinese: "殘酷的", phrase: "", sentence: "It's cruel to treat animals badly."),
Junior_High_School_Word(id: 30, english: "curious", chinese: "好奇的", phrase: "", sentence: "I'm curious to know what happened."),
Junior_High_School_Word(id: 31, english: "embarrass", chinese: "使尷尬", phrase: "", sentence: "It embarrasses me to talk about my achievements."),
Junior_High_School_Word(id: 32, english: "emotion", chinese: "情緒", phrase: "emotional", sentence: "She's a very emotional person."),
Junior_High_School_Word(id: 33, english: "envy", chinese: "羨慕", phrase: "to be envious of", sentence: "I envy her success."),
Junior_High_School_Word(id: 34, english: "excite", chinese: "使興奮", phrase: "", sentence: "The concert really excited the audience."),
Junior_High_School_Word(id: 35, english: "express", chinese: "表達", phrase: "", sentence: "He finds it hard to express his feelings."),
Junior_High_School_Word(id: 36, english: "fear", chinese: "恐懼", phrase: "", sentence: "He has a fear of heights."),
Junior_High_School_Word(id: 37, english: "feeling", chinese: "感覺", phrase: "", sentence: "I have a feeling that something is wrong."),
Junior_High_School_Word(id: 38, english: "frighten", chinese: "使嚇到", phrase: "fright", sentence: "The sudden noise frightened the baby."),
Junior_High_School_Word(id: 39, english: "interest", chinese: "使…感興趣, , 興趣", phrase: "", sentence: "His main interests are music and sports."),
Junior_High_School_Word(id: 40, english: "jealous", chinese: "忌妒的", phrase: "", sentence: "She's jealous of my success."),
Junior_High_School_Word(id: 41, english: "nervous", chinese: "緊張的", phrase: "", sentence: "He gets nervous before public speaking."),
Junior_High_School_Word(id: 42, english: "patience", chinese: "耐心", phrase: "", sentence: "You need to have patience when teaching children."),
Junior_High_School_Word(id: 43, english: "patient", chinese: "有耐心的, , 病人", phrase: "", sentence: "She's very patient with her students."),
Junior_High_School_Word(id: 44, english: "pity", chinese: "憐憫, , 可惜", phrase: "", sentence: "It's a pity that she couldn't come."),
Junior_High_School_Word(id: 45, english: "pleased", chinese: "滿意的", phrase: "", sentence: "I'm pleased with the results."),
Junior_High_School_Word(id: 46, english: "please", chinese: "取悅", phrase: "", sentence: "Music always pleases him."),
Junior_High_School_Word(id: 47, english: "pleasure", chinese: "樂趣", phrase: "", sentence: "It's a pleasure to meet you."),
Junior_High_School_Word(id: 48, english: "pride", chinese: "驕傲", phrase: "", sentence: "She takes pride in her work."),
Junior_High_School_Word(id: 49, english: "proud", chinese: "自豪的", phrase: "to be proud of", sentence: "He's proud of his achievements."),
Junior_High_School_Word(id: 50, english: "relax", chinese: "放鬆", phrase: "relaxed", sentence: "I like to relax by reading a book."),
];

List<Junior_High_School_Word> unit6 = [
Junior_High_School_Word(id: 1, english: "baby", chinese: "嬰兒", phrase: "", sentence: "The baby is sleeping soundly."),
Junior_High_School_Word(id: 2, english: "boy", chinese: "男孩", phrase: "", sentence: "The boy is playing with his toy car."),
Junior_High_School_Word(id: 3, english: "child", chinese: "小孩", phrase: "", sentence: "Every child deserves love and care."),
Junior_High_School_Word(id: 4, english: "ghost", chinese: "鬼", phrase: "", sentence: "Many people believe in ghosts."),
Junior_High_School_Word(id: 5, english: "giant", chinese: "巨人", phrase: "", sentence: "The giant towered over the village."),
Junior_High_School_Word(id: 6, english: "girl", chinese: "女孩", phrase: "", sentence: "The girl is reading a book under the tree."),
Junior_High_School_Word(id: 7, english: "guy", chinese: "傢伙", phrase: "", sentence: "That guy over there is my friend."),
Junior_High_School_Word(id: 8, english: "kid", chinese: "小孩, , 開玩笑", phrase: "", sentence: "Don't kid me, I know what you did."),
Junior_High_School_Word(id: 9, english: "king", chinese: "國王", phrase: "", sentence: "The king ruled his kingdom with wisdom."),
Junior_High_School_Word(id: 10, english: "leader", chinese: "領導人", phrase: "", sentence: "She is a natural leader with charisma."),
Junior_High_School_Word(id: 11, english: "man", chinese: "男人", phrase: "", sentence: "The old man sat on the bench."),
Junior_High_School_Word(id: 12, english: "Miss", chinese: "小姐", phrase: "", sentence: "Miss Johnson is my English teacher."),
Junior_High_School_Word(id: 13, english: "Mr.", chinese: "先生", phrase: "", sentence: "Mr. Smith is the manager of the company."),
Junior_High_School_Word(id: 14, english: "Mrs.", chinese: "太太", phrase: "", sentence: "Mrs. Lee baked some delicious cookies."),
Junior_High_School_Word(id: 15, english: "Ms.", chinese: "女士", phrase: "", sentence: "Ms. Davis is a renowned journalist."),
Junior_High_School_Word(id: 16, english: "name", chinese: "名字, , 取名", phrase: "", sentence: "My name is Alex."),
Junior_High_School_Word(id: 17, english: "neighbor", chinese: "鄰居", phrase: "", sentence: "My neighbors are very friendly."),
Junior_High_School_Word(id: 18, english: "people", chinese: "人們", phrase: "", sentence: "People are gathering at the park."),
Junior_High_School_Word(id: 19, english: "person", chinese: "人們", phrase: "", sentence: "He's the kind of person who always helps others."),
Junior_High_School_Word(id: 20, english: "prince", chinese: "王子", phrase: "", sentence: "The prince is next in line for the throne."),
Junior_High_School_Word(id: 21, english: "princess", chinese: "公主", phrase: "", sentence: "The princess wore a beautiful gown."),
Junior_High_School_Word(id: 22, english: "queen", chinese: "皇后", phrase: "", sentence: "The queen addressed her subjects."),
Junior_High_School_Word(id: 23, english: "sir", chinese: "先生", phrase: "", sentence: "Excuse me, sir, do you have the time?"),
Junior_High_School_Word(id: 24, english: "stranger", chinese: "陌生人", phrase: "", sentence: "Don't talk to strangers."),
Junior_High_School_Word(id: 25, english: "teenager", chinese: "青少年", phrase: "", sentence: "Teenagers often seek independence."),
Junior_High_School_Word(id: 26, english: "woman", chinese: "女人", phrase: "", sentence: "The woman is carrying a basket of flowers."),
Junior_High_School_Word(id: 27, english: "adult", chinese: "成人", phrase: "", sentence: "When I grow up, I want to be a responsible adult."),
Junior_High_School_Word(id: 28, english: "angle", chinese: "天使", phrase: "", sentence: "Note: I believe there's a typo. It should be 'angel' for '天使'. The angel has beautiful wings."),
Junior_High_School_Word(id: 29, english: "audience", chinese: "聽眾", phrase: "", sentence: "The audience gave a standing ovation."),
Junior_High_School_Word(id: 30, english: "beauty", chinese: "美女", phrase: "", sentence: "Beauty is in the eye of the beholder."),
Junior_High_School_Word(id: 31, english: "childhood", chinese: "孩童時期", phrase: "", sentence: "I miss the simplicity of my childhood."),
Junior_High_School_Word(id: 32, english: "citizen", chinese: "公民", phrase: "", sentence: "Every citizen has the right to vote."),
Junior_High_School_Word(id: 33, english: "Confucius", chinese: "孔子", phrase: "", sentence: "Confucius is a famous philosopher from China."),
Junior_High_School_Word(id: 34, english: "couple", chinese: "情侶, , 數個", phrase: "", sentence: "The couple walked hand in hand."),
Junior_High_School_Word(id: 35, english: "creator", chinese: "創作者", phrase: "", sentence: "The creator of the artwork is unknown."),
Junior_High_School_Word(id: 36, english: "customer", chinese: "顧客", phrase: "", sentence: "The customer is always right."),
Junior_High_School_Word(id: 37, english: "Dr.", chinese: "博士, , 醫生", phrase: "", sentence: "Dr. Martin is a renowned surgeon."),
Junior_High_School_Word(id: 38, english: "enemy", chinese: "敵人", phrase: "", sentence: "Keep your friends close and your enemies closer."),
Junior_High_School_Word(id: 39, english: "fellow", chinese: "夥伴", phrase: "", sentence: "He's a fellow student from my university."),
Junior_High_School_Word(id: 40, english: "follower", chinese: "追隨者", phrase: "", sentence: "She has millions of followers on social media."),
Junior_High_School_Word(id: 41, english: "foreigner", chinese: "外國人", phrase: "", sentence: "As a foreigner, he's trying to learn the local customs."),
Junior_High_School_Word(id: 42, english: "fool", chinese: "傻瓜", phrase: "", sentence: "Only a fool would believe such a story."),
Junior_High_School_Word(id: 43, english: "genius", chinese: "天才", phrase: "", sentence: "Einstein was a genius in physics."),
Junior_High_School_Word(id: 44, english: "gentleman", chinese: "紳士", phrase: "", sentence: "He's a true gentleman, always polite and kind."),
Junior_High_School_Word(id: 45, english: "God", chinese: "上帝", phrase: "", sentence: "Many people turn to God in times of need."),
Junior_High_School_Word(id: 46, english: "goddess", chinese: "女神", phrase: "", sentence: "Aphrodite is the goddess of love in Greek mythology."),
Junior_High_School_Word(id: 47, english: "guest", chinese: "客人", phrase: "", sentence: "We have a guest coming over for dinner."),
Junior_High_School_Word(id: 48, english: "hero", chinese: "英雄, , 男主角", phrase: "", sentence: "He's a war hero who saved many lives."),
Junior_High_School_Word(id: 49, english: "host", chinese: "主人", phrase: "", sentence: "The host welcomed everyone to the party."),
Junior_High_School_Word(id: 50, english: "human", chinese: "人類, , 人類的", phrase: "", sentence: "Humans are capable of great compassion."),
Junior_High_School_Word(id: 51, english: "lady", chinese: "女士", phrase: "", sentence: "The old lady lives next door."),
Junior_High_School_Word(id: 52, english: "leadership", chinese: "領導", phrase: "", sentence: "Good leadership is essential for a team's success."),
Junior_High_School_Word(id: 53, english: "loser", chinese: "輸家", phrase: "", sentence: "It's not about winning or losing; it's about trying your best."),
Junior_High_School_Word(id: 54, english: "lover", chinese: "情人, , 愛好者", phrase: "", sentence: "She's a lover of classical music."),
Junior_High_School_Word(id: 55, english: "madam", chinese: "夫人", phrase: "", sentence: "Madam, your table is ready."),
Junior_High_School_Word(id: 56, english: "male", chinese: "男性的", phrase: "female女性的", sentence: "The male lion is known for its majestic mane."),
Junior_High_School_Word(id: 57, english: "master", chinese: "大師, , 碩士", phrase: "", sentence: "He's a master of martial arts."),
Junior_High_School_Word(id: 58, english: "partner", chinese: "夥伴", phrase: "", sentence: "She's my business partner."),
Junior_High_School_Word(id: 59, english: "passenger", chinese: "乘客, , 行人", phrase: "", sentence: "The bus was full of passengers."),
Junior_High_School_Word(id: 60, english: "patient", chinese: "病人, , 有耐心的", phrase: "", sentence: "The doctor is seeing a patient."),
Junior_High_School_Word(id: 61, english: "prisoner", chinese: "囚犯", phrase: "", sentence: "The prisoner was released on parole."),
Junior_High_School_Word(id: 62, english: "robot", chinese: "機器人", phrase: "", sentence: "The robot can perform complex tasks."),
Junior_High_School_Word(id: 63, english: "speaker", chinese: "講者, , 喇叭", phrase: "", sentence: "The speaker delivered an inspiring speech."),
Junior_High_School_Word(id: 64, english: "thief", chinese: "小偷", phrase: "", sentence: "The thief was caught red-handed."),
Junior_High_School_Word(id: 65, english: "user", chinese: "使用者", phrase: "", sentence: "The software is user-friendly."),
Junior_High_School_Word(id: 66, english: "visitor", chinese: "參觀者, , 遊客", phrase: "", sentence: "The museum has many visitors every day."),
Junior_High_School_Word(id: 67, english: "voter", chinese: "投票者", phrase: "", sentence: "Every voter has a voice in the election."),
Junior_High_School_Word(id: 68, english: "winner", chinese: "贏家", phrase: "", sentence: "She's the winner of the competition."),
Junior_High_School_Word(id: 69, english: "youth", chinese: "青年", phrase: "", sentence: "Youth is a time of exploration and discovery."),
];

List<Junior_High_School_Word> unit7 = [
Junior_High_School_Word(id: 1, english: "beautiful", chinese: "美麗的", phrase: "", sentence: "The sunset was incredibly beautiful."),
Junior_High_School_Word(id: 2, english: "blind", chinese: "盲的", phrase: "to turn a blind eye to sth", sentence: "She's blind, but she has an amazing sense of hearing."),
Junior_High_School_Word(id: 3, english: "cute", chinese: "可愛的", phrase: "", sentence: "That puppy is so cute!"),
Junior_High_School_Word(id: 4, english: "fat", chinese: "肥胖的", phrase: "", sentence: "He's been gaining weight; he's getting a bit fat."),
Junior_High_School_Word(id: 5, english: "handsome", chinese: "帥的", phrase: "", sentence: "Many consider him to be the most handsome actor."),
Junior_High_School_Word(id: 6, english: "heavy", chinese: "重的", phrase: "a heavy smoker/drinker", sentence: "This box is too heavy for me to lift."),
Junior_High_School_Word(id: 7, english: "old", chinese: "老的", phrase: "", sentence: "My grandfather is old but very active."),
Junior_High_School_Word(id: 8, english: "pretty", chinese: "漂亮的/非常", phrase: "", sentence: "She's pretty and also very intelligent."),
Junior_High_School_Word(id: 9, english: "short", chinese: "短的/矮的", phrase: "a short cut; be a short of", sentence: "She's short but very athletic."),
Junior_High_School_Word(id: 10, english: "slim", chinese: "苗條的", phrase: "", sentence: "She has a slim figure."),
Junior_High_School_Word(id: 11, english: "tall", chinese: "高的", phrase: "", sentence: "He's the tallest person in our class."),
Junior_High_School_Word(id: 12, english: "thin", chinese: "瘦的/薄的", phrase: "", sentence: "This book is quite thin, only 50 pages."),
Junior_High_School_Word(id: 13, english: "young", chinese: "年輕的", phrase: "", sentence: "She looks very young for her age."),
Junior_High_School_Word(id: 14, english: "appearance", chinese: "外表", phrase: "", sentence: "First impressions are often based on appearance."),
Junior_High_School_Word(id: 15, english: "chubby", chinese: "圓胖的", phrase: "", sentence: "The baby's chubby cheeks are so adorable."),
Junior_High_School_Word(id: 16, english: "deaf", chinese: "聾的", phrase: "to turn a deaf ear to sth", sentence: "He's deaf, so you need to use sign language."),
Junior_High_School_Word(id: 17, english: "dumb", chinese: "啞的/無聲的", phrase: "", sentence: "He's dumb and communicates using gestures."),
Junior_High_School_Word(id: 18, english: "fashionable", chinese: "時髦的", phrase: "", sentence: "She always wears the most fashionable clothes."),
Junior_High_School_Word(id: 19, english: "figure", chinese: "身材", phrase: "", sentence: "She has a figure of a model."),
Junior_High_School_Word(id: 20, english: "fit", chinese: "勻稱的/適合", phrase: "fitness center; gym", sentence: "He goes to the gym regularly to stay fit."),
Junior_High_School_Word(id: 21, english: "haircut", chinese: "理髮", phrase: "", sentence: "I need a new haircut; it's getting too long."),
Junior_High_School_Word(id: 22, english: "nice-looking", chinese: "好看的", phrase: "", sentence: "He's a nice-looking young man."),
Junior_High_School_Word(id: 23, english: "over-weight", chinese: "過重的", phrase: "", sentence: "Being overweight can lead to health issues."),
Junior_High_School_Word(id: 24, english: "skinny", chinese: "皮包骨的", phrase: "", sentence: "He's so skinny; he should eat more."),
Junior_High_School_Word(id: 25, english: "slender", chinese: "纖瘦的", phrase: "", sentence: "She has a slender waist."),
Junior_High_School_Word(id: 26, english: "ugly", chinese: "醜的", phrase: "", sentence: "Beauty and ugliness are subjective."),
Junior_High_School_Word(id: 27, english: "under-weight", chinese: "體重過輕的", phrase: "", sentence: "She's under-weight and needs to gain some."),
Junior_High_School_Word(id: 28, english: "youthful", chinese: "年輕的", phrase: "", sentence: "Despite her age, she has a youthful spirit."),
];


List<Junior_High_School_Word> unit8 = [
Junior_High_School_Word(id: 1, english: "bad", chinese: "壞的", phrase: "bad luck", sentence: "I have bad luck today."),
Junior_High_School_Word(id: 2, english: "bright", chinese: "聰明的", phrase: "bright idea", sentence: "She always has bright ideas."),
Junior_High_School_Word(id: 3, english: "careful", chinese: "謹慎的", phrase: "be careful", sentence: "Be careful when crossing the street."),
Junior_High_School_Word(id: 4, english: "cool", chinese: "酷的, 冷淡的", phrase: "cool down", sentence: "Let's cool down and talk."),
Junior_High_School_Word(id: 5, english: "dirty", chinese: "髒兮兮的, 卑劣的", phrase: "dirty trick", sentence: "He played a dirty trick on me."),
Junior_High_School_Word(id: 6, english: "excellent", chinese: "優秀的", phrase: "excellent job", sentence: "You did an excellent job."),
Junior_High_School_Word(id: 7, english: "famous", chinese: "知名的", phrase: "famous actor", sentence: "He is a famous actor in Hollywood."),
Junior_High_School_Word(id: 8, english: "friendly", chinese: "友善的", phrase: "friendly advice", sentence: "She gave me some friendly advice."),
Junior_High_School_Word(id: 9, english: "funny", chinese: "滑稽的", phrase: "funny joke", sentence: "He told a funny joke."),
Junior_High_School_Word(id: 10, english: "good", chinese: "好的", phrase: "good job", sentence: "You did a good job."),
Junior_High_School_Word(id: 11, english: "great", chinese: "很棒的", phrase: "great effort", sentence: "He made a great effort to succeed."),
Junior_High_School_Word(id: 12, english: "hand-working", chinese: "認真工作的", phrase: "hard-working student", sentence: "She is a hard-working student."),
Junior_High_School_Word(id: 13, english: "honest", chinese: "誠實的", phrase: "honest answer", sentence: "Give me an honest answer."),
Junior_High_School_Word(id: 14, english: "kind", chinese: "仁慈的, 種類", phrase: "kind gesture", sentence: "It was a kind gesture from her."),
Junior_High_School_Word(id: 15, english: "lazy", chinese: "懶惰的", phrase: "lazy afternoon", sentence: "It's a lazy afternoon."),
Junior_High_School_Word(id: 16, english: "lovely", chinese: "可愛的", phrase: "lovely smile", sentence: "She has a lovely smile."),
Junior_High_School_Word(id: 17, english: "mean", chinese: "苛刻的, 壞脾氣的", phrase: "mean person", sentence: "He can be a mean person at times."),
Junior_High_School_Word(id: 18, english: "nice", chinese: "好心的", phrase: "nice gesture", sentence: "That was a nice gesture of you."),
Junior_High_School_Word(id: 19, english: "polite", chinese: "有禮貌的", phrase: "polite request", sentence: "He made a polite request."),
Junior_High_School_Word(id: 20, english: "poor", chinese: "窮困的", phrase: "poor condition", sentence: "The house is in poor condition."),
Junior_High_School_Word(id: 21, english: "popular", chinese: "受歡迎的", phrase: "popular trend", sentence: "This is a popular trend nowadays."),
Junior_High_School_Word(id: 22, english: "proud", chinese: "驕傲的", phrase: "proud moment", sentence: "It was a proud moment for all of us."),
Junior_High_School_Word(id: 23, english: "quiet", chinese: "安靜的", phrase: "quiet place", sentence: "I need a quiet place to study."),
Junior_High_School_Word(id: 24, english: "rich", chinese: "富裕的", phrase: "rich history", sentence: "The city has a rich history."),
Junior_High_School_Word(id: 25, english: "serious", chinese: "嚴肅的, 認真的", phrase: "serious matter", sentence: "This is a serious matter."),
Junior_High_School_Word(id: 26, english: "shy", chinese: "害羞的", phrase: "shy away", sentence: "She tends to shy away from attention."),
Junior_High_School_Word(id: 27, english: "smart", chinese: "聰明的", phrase: "smart choice", sentence: "Making that decision was a smart choice."),
Junior_High_School_Word(id: 28, english: "special", chinese: "特別的", phrase: "special occasion", sentence: "This is a special occasion for us."),
Junior_High_School_Word(id: 29, english: "strange", chinese: "奇怪, 陌生的", phrase: "strange behavior", sentence: "His strange behavior worried us."),
Junior_High_School_Word(id: 30, english: "stupid", chinese: "愚笨的", phrase: "stupid mistake", sentence: "I made a stupid mistake."),
Junior_High_School_Word(id: 31, english: "successful", chinese: "成功的", phrase: "successful attempt", sentence: "It was a successful attempt."),
Junior_High_School_Word(id: 32, english: "wise", chinese: "明智的", phrase: "wise decision", sentence: "It was a wise decision to wait."),
Junior_High_School_Word(id: 33, english: "active", chinese: "有活力的", phrase: "active lifestyle", sentence: "She leads an active lifestyle."),
Junior_High_School_Word(id: 34, english: "brave", chinese: "勇敢的", phrase: "brave heart", sentence: "He has a brave heart."),
Junior_High_School_Word(id: 35, english: "careless", chinese: "粗心的, 不在意的", phrase: "careless mistake", sentence: "It was a careless mistake."),
Junior_High_School_Word(id: 36, english: "clever", chinese: "聰明的", phrase: "clever solution", sentence: "She came up with a clever solution."),
Junior_High_School_Word(id: 37, english: "crazy", chinese: "瘋狂的", phrase: "crazy idea", sentence: "That's a crazy idea!"),
Junior_High_School_Word(id: 38, english: "curious", chinese: "好奇的", phrase: "curious mind", sentence: "Children have a curious mind."),
Junior_High_School_Word(id: 39, english: "eager", chinese: "渴望的", phrase: "eager to learn", sentence: "He is eager to learn new things."),
Junior_High_School_Word(id: 40, english: "easy-going", chinese: "隨和的", phrase: "easy-going personality", sentence: "She has an easy-going personality."),
Junior_High_School_Word(id: 41, english: "energetic", chinese: "有活力的", phrase: "energetic dance", sentence: "She performed an energetic dance."),
Junior_High_School_Word(id: 42, english: "enthusiastic", chinese: "熱情的", phrase: "enthusiastic response", sentence: "We received an enthusiastic response from the audience."),
Junior_High_School_Word(id: 43, english: "fierce", chinese: "兇猛的", phrase: "fierce competition", sentence: "There's a fierce competition in the market."),
Junior_High_School_Word(id: 44, english: "gentle", chinese: "溫柔的", phrase: "gentle touch", sentence: "She has a gentle touch."),
Junior_High_School_Word(id: 45, english: "grumpy", chinese: "脾氣暴躁的", phrase: "grumpy mood", sentence: "He woke up in a grumpy mood."),
Junior_High_School_Word(id: 46, english: "humble", chinese: "謙虛的", phrase: "humble beginnings", sentence: "He came from humble beginnings."),
Junior_High_School_Word(id: 47, english: "jolly", chinese: "快樂的", phrase: "jolly mood", sentence: "She's always in a jolly mood during holidays."),
Junior_High_School_Word(id: 48, english: "lively", chinese: "生氣勃勃的", phrase: "lively discussion", sentence: "We had a lively discussion about the topic."),
Junior_High_School_Word(id: 49, english: "moody", chinese: "喜怒無常的", phrase: "moody behavior", sentence: "He's known for his moody behavior."),
Junior_High_School_Word(id: 50, english: "optimistic", chinese: "樂觀的", phrase: "optimistic outlook", sentence: "She has an optimistic outlook on life."),
Junior_High_School_Word(id: 51, english: "passionate", chinese: "充滿激情的", phrase: "passionate speech", sentence: "He gave a passionate speech about human rights."),
Junior_High_School_Word(id: 52, english: "pessimistic", chinese: "悲觀的", phrase: "pessimistic view", sentence: "He has a pessimistic view about the future."),
Junior_High_School_Word(id: 53, english: "playful", chinese: "好玩的", phrase: "playful attitude", sentence: "The kids have a playful attitude."),
Junior_High_School_Word(id: 54, english: "reserved", chinese: "內向的", phrase: "reserved nature", sentence: "She's known for her reserved nature."),
Junior_High_School_Word(id: 55, english: "sincere", chinese: "真誠的", phrase: "sincere apology", sentence: "He offered a sincere apology."),
Junior_High_School_Word(id: 56, english: "thoughtful", chinese: "體貼的", phrase: "thoughtful gesture", sentence: "It was a thoughtful gesture to bring flowers."),
Junior_High_School_Word(id: 57, english: "vivacious", chinese: "活潑的", phrase: "vivacious personality", sentence: "She has a vivacious personality."),
Junior_High_School_Word(id: 58, english: "warm-hearted", chinese: "熱心的", phrase: "warm-hearted individual", sentence: "My neighbor is a warm-hearted individual."),
Junior_High_School_Word(id: 59, english: "witty", chinese: "機智的", phrase: "witty remark", sentence: "He made a witty remark at the party."),
Junior_High_School_Word(id: 60, english: "adventurous", chinese: "愛冒險的", phrase: "adventurous journey", sentence: "They went on an adventurous journey across the desert."),
Junior_High_School_Word(id: 61, english: "imaginative", chinese: "富有想像力的", phrase: "imaginative story", sentence: "She wrote an imaginative story for the competition."),
Junior_High_School_Word(id: 62, english: "independent", chinese: "獨立的", phrase: "independent thinker", sentence: "He's always been an independent thinker."),
Junior_High_School_Word(id: 63, english: "innocent", chinese: "無辜, 天真的", phrase: "innocent child", sentence: "He looks like an innocent child."),
Junior_High_School_Word(id: 64, english: "intelligent", chinese: "聰明的", phrase: "intelligent student", sentence: "She is the most intelligent student in the class."),
Junior_High_School_Word(id: 65, english: "joyful", chinese: "愉快的", phrase: "joyful occasion", sentence: "It was a joyful occasion for everyone."),
Junior_High_School_Word(id: 66, english: "justice", chinese: "公正, 正義", phrase: "seek justice", sentence: "He went to court to seek justice."),
Junior_High_School_Word(id: 67, english: "kindness", chinese: "仁慈, 親切", phrase: "act of kindness", sentence: "Helping the elderly is an act of kindness."),
Junior_High_School_Word(id: 68, english: "knowledge", chinese: "知識", phrase: "gain knowledge", sentence: "Reading books helps you gain knowledge."),
Junior_High_School_Word(id: 69, english: "loyal", chinese: "忠誠的", phrase: "loyal friend", sentence: "He's been a loyal friend for many years."),
Junior_High_School_Word(id: 70, english: "lucky", chinese: "幸運的", phrase: "lucky charm", sentence: "She always carries her lucky charm with her."),
Junior_High_School_Word(id: 71, english: "mature", chinese: "成熟的", phrase: "mature behavior", sentence: "His mature behavior impressed everyone."),
Junior_High_School_Word(id: 72, english: "modest", chinese: "謙虛的", phrase: "modest person", sentence: "Despite his achievements, he remains a modest person."),
Junior_High_School_Word(id: 73, english: "naughty", chinese: "淘氣的", phrase: "naughty child", sentence: "The naughty child spilled milk everywhere."),
Junior_High_School_Word(id: 74, english: "optimistic", chinese: "樂觀的", phrase: "optimistic view", sentence: "She always has an optimistic view of life."),
Junior_High_School_Word(id: 75, english: "outgoing", chinese: "外向的", phrase: "outgoing personality", sentence: "Her outgoing personality makes her popular."),
Junior_High_School_Word(id: 76, english: "passion", chinese: "熱情, 激情", phrase: "have a passion for", sentence: "She has a passion for dancing."),
Junior_High_School_Word(id: 77, english: "patience", chinese: "耐心", phrase: "have patience", sentence: "You need to have patience while learning a new skill."),
Junior_High_School_Word(id: 78, english: "peace", chinese: "和平", phrase: "long for peace", sentence: "The war-torn country longs for peace."),
Junior_High_School_Word(id: 79, english: "pessimistic", chinese: "悲觀的", phrase: "pessimistic outlook", sentence: "He has a pessimistic outlook on the economy."),
Junior_High_School_Word(id: 80, english: "rational", chinese: "理智的", phrase: "rational decision", sentence: "It's important to make a rational decision in this situation."),
Junior_High_School_Word(id: 81, english: "respect", chinese: "尊重", phrase: "show respect", sentence: "Always show respect to your elders."),
Junior_High_School_Word(id: 82, english: "responsible", chinese: "有責任的", phrase: "be responsible for", sentence: "He is responsible for the project's success."),
Junior_High_School_Word(id: 83, english: "romantic", chinese: "浪漫的", phrase: "romantic dinner", sentence: "They had a romantic dinner by the beach."),
Junior_High_School_Word(id: 84, english: "sensible", chinese: "明智的", phrase: "sensible choice", sentence: "Making a budget is a sensible choice."),
Junior_High_School_Word(id: 85, english: "sensitive", chinese: "敏感的", phrase: "sensitive topic", sentence: "It's a sensitive topic, so tread carefully."),
Junior_High_School_Word(id: 86, english: "stubborn", chinese: "固執的", phrase: "stubborn attitude", sentence: "His stubborn attitude often gets him into trouble."),
Junior_High_School_Word(id: 87, english: "sympathy", chinese: "同情, 同感", phrase: "express sympathy", sentence: "She expressed sympathy for the victims."),
Junior_High_School_Word(id: 88, english: "talent", chinese: "才能, 天資", phrase: "natural talent", sentence: "She has a natural talent for singing."),
Junior_High_School_Word(id: 89, english: "thoughtful", chinese: "體貼的", phrase: "thoughtful gift", sentence: "He gave her a thoughtful gift on her birthday."),
Junior_High_School_Word(id: 90, english: "trust", chinese: "信任, 信賴", phrase: "build trust", sentence: "It takes time to build trust in a relationship."),
Junior_High_School_Word(id: 91, english: "truth", chinese: "真實, 真相", phrase: "seek the truth", sentence: "Journalists should always seek the truth."),
Junior_High_School_Word(id: 92, english: "understanding", chinese: "了解, 諒解", phrase: "show understanding", sentence: "She showed understanding when he explained his situation."),
Junior_High_School_Word(id: 93, english: "unique", chinese: "獨特的", phrase: "unique style", sentence: "She has a unique style of dressing."),
Junior_High_School_Word(id: 94, english: "wisdom", chinese: "智慧", phrase: "share wisdom", sentence: "The elderly often share wisdom from their experiences."),
Junior_High_School_Word(id: 95, english: "wonder", chinese: "驚奇, 奇觀", phrase: "feel wonder", sentence: "I felt wonder when I saw the Northern Lights."),
Junior_High_School_Word(id: 96, english: "youth", chinese: "青春, 年輕", phrase: "celebrate youth", sentence: "The festival is a celebration of youth and energy."),
Junior_High_School_Word(id: 97, english: "zeal", chinese: "熱情, 熱忱", phrase: "show zeal", sentence: "She showed great zeal in promoting the new product."),
Junior_High_School_Word(id: 98, english: "zest", chinese: "熱情, 興趣", phrase: "live with zest", sentence: "He lives his life with zest and enthusiasm."),
Junior_High_School_Word(id: 99, english: "bravery", chinese: "勇敢", phrase: "act of bravery", sentence: "Saving the child was an act of bravery."),
Junior_High_School_Word(id: 100, english: "calm", chinese: "冷靜的", phrase: "stay calm", sentence: "In emergencies, it's important to stay calm."),
Junior_High_School_Word(id: 101, english: "dedication", chinese: "奉獻, 致力", phrase: "show dedication", sentence: "She showed dedication to her work."),
Junior_High_School_Word(id: 102, english: "elegance", chinese: "優雅", phrase: "display elegance", sentence: "She displayed elegance in her dance."),
Junior_High_School_Word(id: 103, english: "freedom", chinese: "自由", phrase: "fight for freedom", sentence: "Many have fought for freedom throughout history."),
Junior_High_School_Word(id: 104, english: "grace", chinese: "優雅, 風度", phrase: "move with grace", sentence: "Ballet dancers move with grace."),
Junior_High_School_Word(id: 105, english: "honesty", chinese: "誠實", phrase: "value honesty", sentence: "I value honesty above all else."),
Junior_High_School_Word(id: 106, english: "integrity", chinese: "正直", phrase: "act with integrity", sentence: "It's important to act with integrity in all situations."),
Junior_High_School_Word(id: 107, english: "joy", chinese: "快樂", phrase: "spread joy", sentence: "Her laughter spreads joy wherever she goes."),
Junior_High_School_Word(id: 108, english: "kind-hearted", chinese: "好心的", phrase: "be kind-hearted", sentence: "She's known to be kind-hearted and generous."),
Junior_High_School_Word(id: 109, english: "loyalty", chinese: "忠誠", phrase: "show loyalty", sentence: "He showed loyalty to his team."),
Junior_High_School_Word(id: 110, english: "magnificent", chinese: "壯觀的", phrase: "magnificent view", sentence: "The mountain offers a magnificent view."),
Junior_High_School_Word(id: 111, english: "noble", chinese: "高尚的", phrase: "noble cause", sentence: "Working for charity is a noble cause."),
Junior_High_School_Word(id: 112, english: "open-minded", chinese: "開放的", phrase: "be open-minded", sentence: "It's beneficial to be open-minded when traveling."),
Junior_High_School_Word(id: 113, english: "pride", chinese: "自豪", phrase: "take pride in", sentence: "She takes pride in her accomplishments."),
Junior_High_School_Word(id: 114, english: "respectful", chinese: "尊敬的", phrase: "be respectful", sentence: "Always be respectful to others."),
Junior_High_School_Word(id: 115, english: "sincere", chinese: "真誠的", phrase: "sincere apology", sentence: "He gave a sincere apology for his actions."),
Junior_High_School_Word(id: 116, english: "tolerant", chinese: "寬容的", phrase: "be tolerant", sentence: "It's important to be tolerant of other cultures."),
Junior_High_School_Word(id: 117, english: "understanding", chinese: "了解的", phrase: "be understanding", sentence: "She was understanding when he explained his reasons."),
Junior_High_School_Word(id: 118, english: "valiant", chinese: "英勇的", phrase: "valiant effort", sentence: "The soldiers made a valiant effort to defend the city."),
Junior_High_School_Word(id: 119, english: "wise", chinese: "明智的", phrase: "wise decision", sentence: "Choosing to study was a wise decision."),
Junior_High_School_Word(id: 120, english: "youthful", chinese: "年輕的", phrase: "youthful energy", sentence: "He has the youthful energy of a teenager."),
];

