
/*
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see <http://www.gnu.org/licenses/>.
 *
 * Author: Nelson Chung
 * Creation Date: September 3, 2023
 */

class Junior_High_School_Word {
	final int id;
	final String english;
	final String chinese;
	final String phrase;
	final String sentence;

	Junior_High_School_Word({required this.id, required this.english, required this.chinese,
							 required this.phrase, required this.sentence});
}

List<Junior_High_School_Word> unit1 = [
	Junior_High_School_Word(id: 1, english: "arm ", chinese: "手臂", phrase: "armpit腋下", sentence: "My brother carried a book under his arm."),
	Junior_High_School_Word(id: 2, english: "back", chinese: "背部\背面\退後", phrase: "behind sb’s back背地裡;to knowsb/sth like the back of sb’s hand對…嘹若指掌", sentence: ""),
	Junior_High_School_Word(id: 3, english: "Bite", chinese: "咬", phrase: "", sentence: ""),
	Junior_High_School_Word(id: 4, english: "blow", chinese: "吹氣", phrase: "", sentence: ""),
	Junior_High_School_Word(id: 5, english: "body", chinese: "身體", phrase: "", sentence: ""),
	Junior_High_School_Word(id: 6, english: "bottom", chinese: "臀部\底部", phrase: "from the bottom of sb’s heart衷心的", sentence: ""),
	Junior_High_School_Word(id: 7, english: "bow", chinese: "鞠躬彎腰", phrase: "", sentence: ""),
	Junior_High_School_Word(id: 8, english: "carry", chinese: "提\運載", phrase: "carrier運送工具", sentence: ""),
	Junior_High_School_Word(id: 9, english: "catch", chinese: "接住\趕上\染上", phrase: "", sentence: ""),
	Junior_High_School_Word(id: 10, english: "clap", chinese: "拍手", phrase: "", sentence: ""),
	Junior_High_School_Word(id: 11, english: "cry", chinese: "哭泣", phrase: "", sentence: ""),
	Junior_High_School_Word(id: 12, english: "drop", chinese: "摔\丟下", phrase: "", sentence: ""),
	Junior_High_School_Word(id: 13, english: "ear", chinese: "耳朵\聽力\音感", phrase: "all ears洗耳恭聽", sentence: ""),
	Junior_High_School_Word(id: 14, english: "eye", chinese: "眼睛\視力\]眼光", phrase: "", sentence: ""),
	Junior_High_School_Word(id: 15, english: "face", chinese: "臉\面對", phrase: "to put on/pull a long face板起臉來;to lose face丟臉/to face thee music面對現實", sentence: ""),
	Junior_High_School_Word(id: 16, english: "fall", chinese: "跌倒", phrase: "", sentence: ""),
	Junior_High_School_Word(id: 17, english: "finger", chinese: "手指", phrase: "", sentence: ""),
	Junior_High_School_Word(id: 18, english: "follow", chinese: "跟隨\在…之後", phrase: "", sentence: ""),
	Junior_High_School_Word(id: 19, english: "foot", chinese: "腳", phrase: "", sentence: ""),
	Junior_High_School_Word(id: 20, english: "hair", chinese: "頭髮", phrase: "straight hair直髮curly hair捲髮", sentence: ""),
	Junior_High_School_Word(id: 21, english: "hand", chinese: "手\交給", phrase: "to give sb a hand幫某人忙;to give sb a big hand為某人鼓掌", sentence: ""),
	Junior_High_School_Word(id: 22, english: "head", chinese: "頭部\頭腦", phrase: "", sentence: ""),
	Junior_High_School_Word(id: 23, english: "heart", chinese: "心臟\感情", phrase: "heart disease心臟病;heart attack心臟病發作", sentence: ""),
	Junior_High_School_Word(id: 24, english: "hit", chinese: "打\碰撞", phrase: "", sentence: ""),
	Junior_High_School_Word(id: 25, english: "hold", chinese: "抓住\舉辦", phrase: "", sentence: ""),
	Junior_High_School_Word(id: 26, english: "hop", chinese: "單腳跳", phrase: "Hip hop嘻哈音樂", sentence: ""),
	Junior_High_School_Word(id: 27, english: "jump", chinese: "跳過", phrase: "", sentence: ""),
	Junior_High_School_Word(id: 28, english: "kick", chinese: "踢", phrase: "", sentence: ""),
	Junior_High_School_Word(id: 29, english: "kiss", chinese: "親吻", phrase: "", sentence: ""),
	Junior_High_School_Word(id: 30, english: "knee", chinese: "膝蓋", phrase: "", sentence: ""),
	Junior_High_School_Word(id: 31, english: "knock", chinese: "敲", phrase: "", sentence: ""),
	Junior_High_School_Word(id: 32, english: "laugh", chinese: "笑聲\發笑", phrase: "to laugh at sb嘲笑 ", sentence: ""),
	Junior_High_School_Word(id: 33, english: "leg", chinese: "腿", phrase: "To pull sb’s leg開某人玩笑", sentence: ""),
	Junior_High_School_Word(id: 34, english: "lie", chinese: "躺\欺騙", phrase: "躺(lie-lay-lain)", sentence: ""),
	Junior_High_School_Word(id: 35, english: "lip", chinese: "嘴唇", phrase: "Lipstick口紅", sentence: ""),
	Junior_High_School_Word(id: 36, english: "mouth", chinese: "嘴吧", phrase: "to speak with sb’s mouth full說話時塞滿嘴吧", sentence: ""),
	Junior_High_School_Word(id: 37, english: "move", chinese: "移動\搬家", phrase: "", sentence: ""),
	Junior_High_School_Word(id: 38, english: "nail", chinese: "指甲", phrase: "", sentence: ""),
	Junior_High_School_Word(id: 39, english: "neck", chinese: "脖子", phrase: "neck and neck並駕齊驅", sentence: ""),
	Junior_High_School_Word(id: 40, english: "nod", chinese: "點頭", phrase: "to nod off打瞌睡", sentence: ""),
	Junior_High_School_Word(id: 41, english: "nose", chinese: "鼻子\嗅覺\辨識能力", phrase: "", sentence: ""),
	Junior_High_School_Word(id: 42, english: "pick", chinese: "摘\挖", phrase: "", sentence: ""),
	Junior_High_School_Word(id: 43, english: "point", chinese: "指著\分數\重點", phrase: "", sentence: ""),
	Junior_High_School_Word(id: 44, english: "pull", chinese: "拉\拖", phrase: "to put off延期", sentence: ""),
	Junior_High_School_Word(id: 45, english: "push", chinese: "推\促使", phrase: "", sentence: ""),
	Junior_High_School_Word(id: 46, english: "put", chinese: "放\擺", phrase: "", sentence: ""),
	Junior_High_School_Word(id: 47, english: "run", chinese: "跑\經營", phrase: "", sentence: ""),
	Junior_High_School_Word(id: 48, english: "shake", chinese: "握手\搖頭", phrase: "", sentence: ""),
	Junior_High_School_Word(id: 49, english: "shoulder", chinese: "肩膀", phrase: "shoulderto shoulder肩並肩 ", sentence: ""),
	Junior_High_School_Word(id: 50, english: "shout", chinese: "喊叫", phrase: "", sentence: ""),
	Junior_High_School_Word(id: 51, english: "sight", chinese: "視力\觀看", phrase: "", sentence: ""),
	Junior_High_School_Word(id: 52, english: "sign", chinese: "手勢\信號\簽名", phrase: "sign language手語", sentence: ""),
	Junior_High_School_Word(id: 53, english: "sit", chinese: "坐", phrase: "", sentence: ""),
	Junior_High_School_Word(id: 54, english: "sleep", chinese: "睡", phrase: "", sentence: ""),
	Junior_High_School_Word(id: 55, english: "smile", chinese: "微笑\笑", phrase: "", sentence: ""),
	Junior_High_School_Word(id: 56, english: "stand", chinese: "站立", phrase: "", sentence: ""),
	Junior_High_School_Word(id: 57, english: "stomach", chinese: "胃\肚子", phrase: "to turn sb’s stomach使某人反胃", sentence: ""),
	Junior_High_School_Word(id: 58, english: "throat", chinese: "喉嚨", phrase: "", sentence: ""),
	Junior_High_School_Word(id: 59, english: "throw", chinese: "丟", phrase: "", sentence: ""),
	Junior_High_School_Word(id: 60, english: "toe", chinese: "腳趾", phrase: "", sentence: ""),
	Junior_High_School_Word(id: 61, english: "tooth", chinese: "牙齒", phrase: "", sentence: ""),
	Junior_High_School_Word(id: 62, english: "voice", chinese: "聲音", phrase: "", sentence: ""),
	Junior_High_School_Word(id: 63, english: "walk", chinese: "走路", phrase: "talk a walk散步", sentence: ""),
	Junior_High_School_Word(id: 64, english: "wave", chinese: "招手", phrase: "", sentence: ""),
	Junior_High_School_Word(id: 65, english: "ankle", chinese: "足踝", phrase: "", sentence: ""),
	Junior_High_School_Word(id: 66, english: "beard", chinese: "鬍子", phrase: "", sentence: ""),
	Junior_High_School_Word(id: 67, english: "beat", chinese: "心跳聲\打\擊敗", phrase: "", sentence: ""),
	Junior_High_School_Word(id: 68, english: "blood", chinese: "血", phrase: "", sentence: ""),
	Junior_High_School_Word(id: 69, english: "bone", chinese: "骨頭", phrase: "", sentence: ""),
	Junior_High_School_Word(id: 70, english: "brain", chinese: "腦子\大腦", phrase: "", sentence: ""),
	Junior_High_School_Word(id: 71, english: "chase", chinese: "追", phrase: "", sentence: ""),
	Junior_High_School_Word(id: 72, english: "flow", chinese: "流動", phrase: "", sentence: ""),
	Junior_High_School_Word(id: 73, english: "gesture", chinese: "手勢", phrase: "", sentence: ""),
	Junior_High_School_Word(id: 74, english: "hip", chinese: "臀部", phrase: "", sentence: ""),
	Junior_High_School_Word(id: 75, english: "hug", chinese: "擁抱", phrase: "", sentence: ""),
	Junior_High_School_Word(id: 76, english: "joint", chinese: "關節", phrase: "", sentence: ""),
	Junior_High_School_Word(id: 77, english: "lay", chinese: "放置", phrase: "", sentence: ""),
	Junior_High_School_Word(id: 78, english: "lick", chinese: "舔", phrase: "", sentence: ""),
	Junior_High_School_Word(id: 79, english: "lift", chinese: "抬\舉", phrase: "", sentence: ""),
	Junior_High_School_Word(id: 80, english: "motion", chinese: "動作\移動", phrase: "", sentence: ""),
	Junior_High_School_Word(id: 81, english: "movement", chinese: "動作\移動", phrase: "", sentence: ""),
	Junior_High_School_Word(id: 82, english: "press", chinese: "按壓\熨燙\印刷機", phrase: "", sentence: ""),
	Junior_High_School_Word(id: 83, english: "print", chinese: "指紋\印刷", phrase: "fingerprint指紋;footprint腳印", sentence: ""),
	Junior_High_School_Word(id: 84, english: "rub", chinese: "搓揉\抓", phrase: "", sentence: ""),
	Junior_High_School_Word(id: 85, english: "sense", chinese: "感覺\感覺到", phrase: "to make sence有道理", sentence: ""),
	Junior_High_School_Word(id: 86, english: "skin", chinese: "皮膚\獸皮", phrase: "skin-deep膚淺的 ", sentence: ""),
	Junior_High_School_Word(id: 87, english: "slip", chinese: "滑倒\滑跤", phrase: "", sentence: ""),
	Junior_High_School_Word(id: 88, english: "soul", chinese: "靈魂\內涵", phrase: "", sentence: ""),
	Junior_High_School_Word(id: 89, english: "step", chinese: "步伐\踏", phrase: "", sentence: ""),
	Junior_High_School_Word(id: 90, english: "thumb", chinese: "拇指", phrase: "", sentence: ""),
	Junior_High_School_Word(id: 91, english: "view", chinese: "看\觀點\景色", phrase: "", sentence: ""),
	Junior_High_School_Word(id: 92, english: "waist", chinese: "腰部", phrase: "", sentence: ""),
	Junior_High_School_Word(id: 93, english: "wrist", chinese: "手腕", phrase: "", sentence: ""),
	Junior_High_School_Word(id: 94, english: "yell", chinese: "大叫", phrase: "", sentence: "")
];

List<Junior_High_School_Word> unit2 = [
  Junior_High_School_Word(id: 1, english: "aunt", chinese: "阿姨", phrase: "", sentence: ""),
  Junior_High_School_Word(id: 2, english: "born", chinese: "出生的\\天生的", phrase: "", sentence: ""),
  Junior_High_School_Word(id: 3, english: "brother", chinese: "兄弟", phrase: "", sentence: ""),
  Junior_High_School_Word(id: 4, english: "cousin", chinese: "表\\堂兄弟", phrase: "", sentence: ""),
  Junior_High_School_Word(id: 5, english: "daughter", chinese: "女兒", phrase: "", sentence: ""),
  Junior_High_School_Word(id: 6, english: "family", chinese: "家庭\\一家人", phrase: "", sentence: ""),
  Junior_High_School_Word(id: 7, english: "father", chinese: "父親", phrase: "", sentence: ""),
  Junior_High_School_Word(id: 8, english: "grandfather", chinese: "祖父", phrase: "", sentence: ""),
  Junior_High_School_Word(id: 9, english: "grandmother", chinese: "祖母", phrase: "", sentence: ""),
  Junior_High_School_Word(id: 10, english: "grow", chinese: "成長", phrase: "", sentence: ""),
  Junior_High_School_Word(id: 11, english: "husband", chinese: "丈夫", phrase: "", sentence: ""),
  Junior_High_School_Word(id: 12, english: "live", chinese: "住\\現場直播的", phrase: "living生計", sentence: ""),
  Junior_High_School_Word(id: 13, english: "married", chinese: "已婚的", phrase: "", sentence: ""),
  Junior_High_School_Word(id: 14, english: "mother", chinese: "母親", phrase: "", sentence: ""),
  Junior_High_School_Word(id: 15, english: "parent", chinese: "雙親中的一位", phrase: "", sentence: ""),
  Junior_High_School_Word(id: 16, english: "raise", chinese: "撫養\\舉起", phrase: "", sentence: ""),
  Junior_High_School_Word(id: 17, english: "sister", chinese: "姊妹", phrase: "", sentence: ""),
  Junior_High_School_Word(id: 18, english: "son", chinese: "兒子", phrase: "son-in-law女婿", sentence: ""),
  Junior_High_School_Word(id: 19, english: "uncle", chinese: "舅舅\\叔叔", phrase: "", sentence: ""),
  Junior_High_School_Word(id: 20, english: "wife", chinese: "妻子", phrase: "", sentence: ""),
  Junior_High_School_Word(id: 21, english: "affair", chinese: "事務\\事件", phrase: "", sentence: ""),
  Junior_High_School_Word(id: 22, english: "affect", chinese: "影響", phrase: "", sentence: ""),
  Junior_High_School_Word(id: 23, english: "elder", chinese: "較年長的人\\較年長的", phrase: "vs.older,elder指兩者中年紀較大的", sentence: ""),
  Junior_High_School_Word(id: 24, english: "generation", chinese: "世代", phrase: "generation gap代溝", sentence: ""),
  Junior_High_School_Word(id: 25, english: "granddaughter", chinese: "孫女", phrase: "", sentence: ""),
  Junior_High_School_Word(id: 26, english: "grandson", chinese: "孫子", phrase: "", sentence: ""),
  Junior_High_School_Word(id: 27, english: "growth", chinese: "成長", phrase: "", sentence: ""),
  Junior_High_School_Word(id: 28, english: "marriage", chinese: "婚姻\\婚禮", phrase: "", sentence: ""),
  Junior_High_School_Word(id: 29, english: "marry", chinese: "結婚", phrase: "", sentence: ""),
  Junior_High_School_Word(id: 30, english: "member", chinese: "成員", phrase: "membership會員資格", sentence: ""),
  Junior_High_School_Word(id: 31, english: "nephew", chinese: "姪子\\外甥", phrase: "", sentence: ""),
  Junior_High_School_Word(id: 32, english: "niece", chinese: "姪女\\外甥女", phrase: "", sentence: ""),
  Junior_High_School_Word(id: 33, english: "relation", chinese: "親戚\\關係", phrase: "bear no\\little\\some relation to與…無關", sentence: ""),
  Junior_High_School_Word(id: 34, english: "relative", chinese: "親戚\\", phrase: "", sentence: ""),
  Junior_High_School_Word(id: 35, english: "role", chinese: "角色", phrase: "", sentence: ""),
  Junior_High_School_Word(id: 36, english: "single", chinese: "單身的", phrase: "", sentence: ""),
  Junior_High_School_Word(id: 37, english: "support", chinese: "資助\\支持", phrase: "", sentence: ""),
  Junior_High_School_Word(id: 38, english: "tradition", chinese: "傳統", phrase: "", sentence: ""),
  Junior_High_School_Word(id: 39, english: "wedding", chinese: "婚禮", phrase: "bride新娘;bridegroom新郎;bridesmaid伴娘;best man伴郎", sentence: ""),
  Junior_High_School_Word(id: 40, english: "related", chinese: "有親戚關係的\\有關連的", phrase: "", sentence: ""),
];

List<Junior_High_School_Word> unit3 = [
	Junior_High_School_Word(id: 1, english: "actor", chinese: "男演員", phrase: "", sentence: ""),
	Junior_High_School_Word(id: 2, english: "actress", chinese: "女演員", phrase: "", sentence: ""),
	Junior_High_School_Word(id: 3, english: "boss", chinese: "老闆", phrase: "", sentence: ""),
	Junior_High_School_Word(id: 4, english: "business", chinese: "生意\\職責", phrase: "on business出差;none of sb's business無關某人的事", sentence: ""),
	Junior_High_School_Word(id: 5, english: "businessman", chinese: "商人", phrase: "", sentence: ""),
	Junior_High_School_Word(id: 6, english: "clerk", chinese: "店員\\職員", phrase: "", sentence: ""),
	Junior_High_School_Word(id: 7, english: "cook", chinese: "廚師", phrase: "cooker鍋子\\火爐", sentence: ""),
	Junior_High_School_Word(id: 8, english: "dentist", chinese: "牙醫", phrase: "", sentence: ""),
	Junior_High_School_Word(id: 9, english: "doctor", chinese: "醫生", phrase: "", sentence: ""),
	Junior_High_School_Word(id: 10, english: "drive", chinese: "司機", phrase: "", sentence: ""),
    Junior_High_School_Word(id: 11, english: "engineer", chinese: "工程師", phrase: "", sentence: ""),
	Junior_High_School_Word(id: 12, english: "farmer", chinese: "農夫", phrase: "", sentence: ""),
	Junior_High_School_Word(id: 13, english: "fisherman", chinese: "漁夫", phrase: "", sentence: ""),
	Junior_High_School_Word(id: 14, english: "interview", chinese: "面試", phrase: "", sentence: ""),
	Junior_High_School_Word(id: 15, english: "job", chinese: "工作", phrase: "a part-time job兼職工作", sentence: ""),
	Junior_High_School_Word(id: 16, english: "lawyer", chinese: "律師", phrase: "", sentence: ""),
	Junior_High_School_Word(id: 17, english: "mailman", chinese: "郵差", phrase: "", sentence: ""),
	Junior_High_School_Word(id: 18, english: "meeting", chinese: "會議", phrase: "to be at a meeting", sentence: ""),
	Junior_High_School_Word(id: 19, english: "nurse", chinese: "護理師", phrase: "", sentence: ""),
	Junior_High_School_Word(id: 20, english: "own", chinese: "擁有\\自己的", phrase: "on sb's own=by oneself獨自的", sentence: ""),
	Junior_High_School_Word(id: 21, english: "police officer", chinese: "警察", phrase: "", sentence: ""),
	Junior_High_School_Word(id: 22, english: "reporter", chinese: "記者", phrase: "", sentence: ""),
	Junior_High_School_Word(id: 23, english: "salesman", chinese: "推銷員", phrase: "", sentence: ""),
	Junior_High_School_Word(id: 24, english: "secretary", chinese: "秘書", phrase: "", sentence: ""),
	Junior_High_School_Word(id: 25, english: "shopkeeper", chinese: "店主", phrase: "storekeeper", sentence: ""),
    Junior_High_School_Word(id: 26, english: "singer", chinese: "歌手", phrase: "", sentence: ""),
    Junior_High_School_Word(id: 27, english: "soldier", chinese: "軍人", phrase: "", sentence: ""),
    Junior_High_School_Word(id: 28, english: "waiter", chinese: "男服務生", phrase: "", sentence: ""),
    Junior_High_School_Word(id: 29, english: "waitress", chinese: "女服務生", phrase: "", sentence: ""),
    Junior_High_School_Word(id: 30, english: "housewife", chinese: "家庭主婦", phrase: "", sentence: ""),
    Junior_High_School_Word(id: 31, english: "work", chinese: "工作", phrase: "", sentence: ""),
    Junior_High_School_Word(id: 32, english: "worker", chinese: "工人", phrase: "", sentence: ""),
    Junior_High_School_Word(id: 33, english: "writer", chinese: "作家", phrase: "", sentence: ""),
    Junior_High_School_Word(id: 34, english: "ability", chinese: "能力", phrase: "", sentence: ""),
    Junior_High_School_Word(id: 35, english: "adviser", chinese: "顧問", phrase: "", sentence: ""),
    Junior_High_School_Word(id: 36, english: "army", chinese: "陸軍", phrase: "army\navy\air force陸海空三軍", sentence: ""),
    Junior_High_School_Word(id: 37, english: "artist", chinese: "藝術家", phrase: "", sentence: ""),
    Junior_High_School_Word(id: 38, english: "assistant", chinese: "助理", phrase: "", sentence: ""),
    Junior_High_School_Word(id: 39, english: "babysitter", chinese: "臨時保母", phrase: "", sentence: ""),
    Junior_High_School_Word(id: 40, english: "banker", chinese: "銀行員", phrase: "", sentence: ""),
    Junior_High_School_Word(id: 41, english: "barker", chinese: "男理髮師", phrase: "hairdresser女理髮師", sentence: ""),
    Junior_High_School_Word(id: 42, english: "builder", chinese: "建築工人", phrase: "", sentence: ""),
    Junior_High_School_Word(id: 43, english: "career", chinese: "職業", phrase: "", sentence: ""),
    Junior_High_School_Word(id: 44, english: "chairman", chinese: "系主任\\董事長", phrase: "", sentence: ""),
    Junior_High_School_Word(id: 45, english: "chief", chinese: "首長", phrase: "", sentence: ""),
    Junior_High_School_Word(id: 46, english: "coach", chinese: "教練", phrase: "", sentence: ""),
    Junior_High_School_Word(id: 47, english: "collector", chinese: "收藏家", phrase: "", sentence: ""),
    Junior_High_School_Word(id: 48, english: "company", chinese: "公司", phrase: "", sentence: ""),
    Junior_High_School_Word(id: 49, english: "cowboy", chinese: "牛仔", phrase: "", sentence: ""),
    Junior_High_School_Word(id: 50, english: "dealer", chinese: "商人", phrase: "", sentence: ""),
    Junior_High_School_Word(id: 51, english: "designer", chinese: "設計師", phrase: "", sentence: ""),
    Junior_High_School_Word(id: 52, english: "diplomat", chinese: "外交官", phrase: "", sentence: ""),
    Junior_High_School_Word(id: 53, english: "director", chinese: "導演", phrase: "", sentence: ""),
    Junior_High_School_Word(id: 54, english: "dramatist", chinese: "劇作家", phrase: "", sentence: ""),
    Junior_High_School_Word(id: 55, english: "educator", chinese: "教育學者", phrase: "", sentence: ""),
    Junior_High_School_Word(id: 56, english: "electrician", chinese: "電工", phrase: "", sentence: ""),
    Junior_High_School_Word(id: 57, english: "employ", chinese: "雇用", phrase: "fire解雇", sentence: ""),
    Junior_High_School_Word(id: 58, english: "employee", chinese: "雇員", phrase: "", sentence: ""),
    Junior_High_School_Word(id: 59, english: "employer", chinese: "雇主", phrase: "", sentence: ""),
    Junior_High_School_Word(id: 60, english: "firm", chinese: "公司\\穩固的", phrase: "", sentence: ""),
    Junior_High_School_Word(id: 61, english: "governor", chinese: "州長\\管理者", phrase: "", sentence: ""),
    Junior_High_School_Word(id: 62, english: "guard", chinese: "警衛\\保全", phrase: "lifeguard救生員;life buoy救生圈", sentence: ""),
    Junior_High_School_Word(id: 63, english: "guide", chinese: "嚮導", phrase: "", sentence: ""),
    Junior_High_School_Word(id: 64, english: "hire", chinese: "租用\\雇用", phrase: "", sentence: ""),
    Junior_High_School_Word(id: 65, english: "historian", chinese: "歷史學家", phrase: "", sentence: ""),
    Junior_High_School_Word(id: 66, english: "hunter", chinese: "獵人", phrase: "", sentence: ""),
    Junior_High_School_Word(id: 67, english: "industry", chinese: "工業", phrase: "", sentence: ""),
    Junior_High_School_Word(id: 68, english: "journalist", chinese: "新聞工作者", phrase: "", sentence: ""),
    Junior_High_School_Word(id: 69, english: "judge", chinese: "評審\\法官\\判斷", phrase: "", sentence: ""),
    Junior_High_School_Word(id: 70, english: "magician", chinese: "魔術師", phrase: "", sentence: ""),
    Junior_High_School_Word(id: 71, english: "manager", chinese: "經理", phrase: "", sentence: ""),
    Junior_High_School_Word(id: 72, english: "mechanic", chinese: "技工", phrase: "", sentence: ""),
    Junior_High_School_Word(id: 73, english: "military", chinese: "軍隊\\軍事的", phrase: "", sentence: ""),
    Junior_High_School_Word(id: 74, english: "model", chinese: "模特兒", phrase: "", sentence: ""),
    Junior_High_School_Word(id: 75, english: "musician", chinese: "音樂家", phrase: "", sentence: ""),
    Junior_High_School_Word(id: 76, english: "occupation", chinese: "職業", phrase: "", sentence: ""),
    Junior_High_School_Word(id: 77, english: "official", chinese: "公務員", phrase: "", sentence: ""),
    Junior_High_School_Word(id: 78, english: "operator", chinese: "操作員\\接線生", phrase: "", sentence: ""),
    Junior_High_School_Word(id: 79, english: "owner", chinese: "所有人", phrase: "ownership所有權", sentence: ""),
    Junior_High_School_Word(id: 80, english: "painter", chinese: "畫家", phrase: "", sentence: ""),
    Junior_High_School_Word(id: 81, english: "personnel", chinese: "全體員工", phrase: "", sentence: ""),
    Junior_High_School_Word(id: 82, english: "photographer", chinese: "攝影師", phrase: "", sentence: ""),
    Junior_High_School_Word(id: 83, english: "physician", chinese: "內科醫生", phrase: "", sentence: ""),
    Junior_High_School_Word(id: 84, english: "physicist", chinese: "物理學家", phrase: "", sentence: ""),
    Junior_High_School_Word(id: 85, english: "president", chinese: "總統\\董事長", phrase: "", sentence: ""),
    Junior_High_School_Word(id: 86, english: "priest", chinese: "牧師", phrase: "", sentence: ""),
    Junior_High_School_Word(id: 87, english: "printer", chinese: "印刷業者\\印表機", phrase: "", sentence: ""),
    Junior_High_School_Word(id: 88, english: "produce", chinese: "生產", phrase: "", sentence: ""),
    Junior_High_School_Word(id: 89, english: "product", chinese: "品", phrase: "", sentence: ""),
    Junior_High_School_Word(id: 90, english: "production", chinese: "產量", phrase: "", sentence: ""),
    Junior_High_School_Word(id: 91, english: "profession", chinese: "職業", phrase: "", sentence: ""),
    Junior_High_School_Word(id: 92, english: "profrssor", chinese: "教授", phrase: "", sentence: ""),
    Junior_High_School_Word(id: 93, english: "rent", chinese: "租用\\租金", phrase: "", sentence: ""),
    Junior_High_School_Word(id: 94, english: "sailor", chinese: "航海員", phrase: "", sentence: ""),
    Junior_High_School_Word(id: 95, english: "scientist", chinese: "科學家", phrase: "", sentence: ""),
    Junior_High_School_Word(id: 96, english: "servant", chinese: "雇工\\僕人", phrase: "", sentence: ""),
    Junior_High_School_Word(id: 97, english: "serve", chinese: "供應\\為…工作", phrase: "", sentence: ""),
    Junior_High_School_Word(id: 98, english: "trade", chinese: "交易\\商業", phrase: "", sentence: ""),
    Junior_High_School_Word(id: 99, english: "trader", chinese: "商人", phrase: "", sentence: ""),
    Junior_High_School_Word(id: 100, english: "vender", chinese: "小販", phrase: "", sentence: ""),
];

List<Junior_High_School_Word> unit4 = [
    Junior_High_School_Word(id: 1, english: "cold", chinese: "感冒", phrase: "", sentence: ""),
    Junior_High_School_Word(id: 2, english: "comfortable", chinese: "舒服的", phrase: "", sentence: ""),
    Junior_High_School_Word(id: 3, english: "dead", chinese: "死去的", phrase: "", sentence: ""),
    Junior_High_School_Word(id: 4, english: "die", chinese: "死亡", phrase: "", sentence: ""),
    Junior_High_School_Word(id: 5, english: "fever", chinese: "發燒", phrase: "", sentence: ""),
    Junior_High_School_Word(id: 6, english: "fine", chinese: "健康的", phrase: "", sentence: ""),
    Junior_High_School_Word(id: 7, english: "headache", chinese: "頭痛", phrase: "", sentence: ""),
    Junior_High_School_Word(id: 8, english: "health", chinese: "健康的", phrase: "", sentence: ""),
    Junior_High_School_Word(id: 9, english: "healthy", chinese: "健康的", phrase: "", sentence: ""),
    Junior_High_School_Word(id: 10, english: "hurt", chinese: "受傷的\\傷害", phrase: "", sentence: ""),
    Junior_High_School_Word(id: 11, english: "life", chinese: "生命", phrase: "", sentence: ""),
    Junior_High_School_Word(id: 12, english: "medicine", chinese: "藥", phrase: "", sentence: ""),
    Junior_High_School_Word(id: 13, english: "sick", chinese: "生病的", phrase: "", sentence: "sickness疾病"),
    Junior_High_School_Word(id: 14, english: "strong", chinese: "強壯的", phrase: "", sentence: ""),
    Junior_High_School_Word(id: 15, english: "sore throat", chinese: "喉嚨痛", phrase: "", sentence: ""),
    Junior_High_School_Word(id: 16, english: "strong", chinese: "強壯的", phrase: "", sentence: ""),
    Junior_High_School_Word(id: 17, english: "tired", chinese: "疲累的", phrase: "", sentence: ""),
    Junior_High_School_Word(id: 18, english: "weak", chinese: "虛弱的", phrase: "", sentence: ""),
    Junior_High_School_Word(id: 19, english: "well", chinese: "良好的\\好地", phrase: "", sentence: ""),
    Junior_High_School_Word(id: 20, english: "AIDS", chinese: "愛滋病", phrase: "", sentence: ""),
    Junior_High_School_Word(id: 21, english: "cancer", chinese: "癌症", phrase: "", sentence: ""),
    Junior_High_School_Word(id: 22, english: "cough", chinese: "咳嗽", phrase: "", sentence: ""),
    Junior_High_School_Word(id: 23, english: "cure", chinese: "治療", phrase: "", sentence: ""),
    Junior_High_School_Word(id: 24, english: "death", chinese: "死亡", phrase: "", sentence: ""),
    Junior_High_School_Word(id: 25, english: "dizzy", chinese: "暈眩的", phrase: "", sentence: ""),
    Junior_High_School_Word(id: 26, english: "drug", chinese: "藥品", phrase: "", sentence: ""),
    Junior_High_School_Word(id: 27, english: "drugstore", chinese: "藥局", phrase: "", sentence: ""),
    Junior_High_School_Word(id: 28, english: "ease", chinese: "減輕", phrase: "", sentence: "disease疾病"),
    Junior_High_School_Word(id: 29, english: "effect", chinese: "效用\\影響", phrase: "", sentence: "side effects副作用"),
    Junior_High_School_Word(id: 30, english: "flu", chinese: "流行性感冒", phrase: "", sentence: ""),
    Junior_High_School_Word(id: 31, english: "homesick", chinese: "想家的", phrase: "", sentence: ""),
    Junior_High_School_Word(id: 32, english: "hunger", chinese: "飢餓", phrase: "", sentence: ""),
    Junior_High_School_Word(id: 33, english: "ill", chinese: "生病的", phrase: "", sentence: ""),
    Junior_High_School_Word(id: 34, english: "injury", chinese: "受傷", phrase: "", sentence: ""),
    Junior_High_School_Word(id: 35, english: "medical", chinese: "醫療的", phrase: "", sentence: ""),
    Junior_High_School_Word(id: 36, english: "pain", chinese: "痛", phrase: "", sentence: ""),
    Junior_High_School_Word(id: 37, english: "painful", chinese: "痛苦的", phrase: "", sentence: ""),
    Junior_High_School_Word(id: 38, english: "pale", chinese: "蒼白的", phrase: "", sentence: ""),
    Junior_High_School_Word(id: 39, english: "physical", chinese: "身體的", phrase: "", sentence: ""),
    Junior_High_School_Word(id: 40, english: "poison", chinese: "毒藥", phrase: "", sentence: ""),
    Junior_High_School_Word(id: 41, english: "recover", chinese: "康復", phrase: "", sentence: ""),
    Junior_High_School_Word(id: 42, english: "sleepy", chinese: "想睡覺的", phrase: "", sentence: ""),
    Junior_High_School_Word(id: 43, english: "stomachache", chinese: "胃痛", phrase: "", sentence: ""),
    Junior_High_School_Word(id: 44, english: "toothache", chinese: "牙痛", phrase: "", sentence: ""),
    Junior_High_School_Word(id: 45, english: "treatment", chinese: "治療\\對待", phrase: "", sentence: ""),
    Junior_High_School_Word(id: 46, english: "wound", chinese: "傷口\\使受傷", phrase: "", sentence: ""),
];


List<Junior_High_School_Word> unit5 = [
    Junior_High_School_Word(id: 1, english: "afraid", chinese: "害怕的", phrase: "to be afraid that", sentence: "恐怕…"),
    Junior_High_School_Word(id: 2, english: "anger", chinese: "怒氣", phrase: "", sentence: ""),
    Junior_High_School_Word(id: 3, english: "angry", chinese: "生氣的", phrase: "", sentence: ""),
    Junior_High_School_Word(id: 4, english: "bored", chinese: "感到無聊的", phrase: "", sentence: ""),
    Junior_High_School_Word(id: 5, english: "boring", chinese: "令人無聊的", phrase: "", sentence: ""),
    Junior_High_School_Word(id: 6, english: "busy", chinese: "忙碌的", phrase: "to busy in", sentence: "忙於做某事"),
    Junior_High_School_Word(id: 7, english: "care", chinese: "在乎關心", phrase: "to care for", sentence: "喜歡\\想要 用於問句"),
    Junior_High_School_Word(id: 8, english: "crazy", chinese: "瘋狂的", phrase: "", sentence: ""),
    Junior_High_School_Word(id: 9, english: "excited", chinese: "感到興奮的", phrase: "", sentence: ""),
    Junior_High_School_Word(id: 10, english: "exciting", chinese: "令人興奮的", phrase: "", sentence: ""),
    Junior_High_School_Word(id: 11, english: "glad", chinese: "高興的", phrase: "", sentence: ""),
    Junior_High_School_Word(id: 12, english: "happy", chinese: "快樂的", phrase: "", sentence: ""),
    Junior_High_School_Word(id: 13, english: "interested", chinese: "感到興趣的", phrase: "", sentence: ""),
    Junior_High_School_Word(id: 14, english: "interesting", chinese: "有趣的", phrase: "", sentence: ""),
    Junior_High_School_Word(id: 15, english: "joy", chinese: "喜悅", phrase: "", sentence: ""),
    Junior_High_School_Word(id: 16, english: "lonely", chinese: "孤單的", phrase: "", sentence: ""),
    Junior_High_School_Word(id: 17, english: "mad", chinese: "生氣的", phrase: "", sentence: ""),
    Junior_High_School_Word(id: 18, english: "please", chinese: "取悅", phrase: "", sentence: ""),
    Junior_High_School_Word(id: 19, english: "surprise", chinese: "驚喜\\使驚訝", phrase: "", sentence: ""),
    Junior_High_School_Word(id: 20, english: "surprised", chinese: "感到驚訝的", phrase: "", sentence: ""),
    Junior_High_School_Word(id: 21, english: "terrible", chinese: "糟糕的", phrase: "", sentence: ""),
    Junior_High_School_Word(id: 22, english: "unhappy", chinese: "不快樂的", phrase: "", sentence: ""),
    Junior_High_School_Word(id: 23, english: "worry", chinese: "擔憂\\擔憂的事", phrase: "", sentence: ""),
    Junior_High_School_Word(id: 24, english: "burst", chinese: "突然出聲\\爆裂", phrase: "", sentence: ""),
    Junior_High_School_Word(id: 25, english: "calm", chinese: "鎮靜的\\平靜下來", phrase: "", sentence: ""),
    Junior_High_School_Word(id: 26, english: "complain", chinese: "抱怨", phrase: "complaint", sentence: "抱怨"),
    Junior_High_School_Word(id: 27, english: "concern", chinese: "擔心", phrase: "", sentence: ""),
    Junior_High_School_Word(id: 28, english: "confuse", chinese: "使困擾", phrase: "", sentence: ""),
    Junior_High_School_Word(id: 29, english: "cruel", chinese: "殘酷的", phrase: "", sentence: ""),
    Junior_High_School_Word(id: 30, english: "curious", chinese: "好奇的", phrase: "", sentence: ""),
    Junior_High_School_Word(id: 31, english: "embarrass", chinese: "使尷尬", phrase: "", sentence: ""),
    Junior_High_School_Word(id: 32, english: "emotion", chinese: "情緒", phrase: "emotional", sentence: "情感的"),
    Junior_High_School_Word(id: 33, english: "envy", chinese: "羨慕", phrase: "to be envious of", sentence: "對…感到羨慕的"),
    Junior_High_School_Word(id: 34, english: "excite", chinese: "使興奮", phrase: "", sentence: ""),
    Junior_High_School_Word(id: 35, english: "express", chinese: "表達", phrase: "", sentence: ""),
    Junior_High_School_Word(id: 36, english: "fear", chinese: "恐懼", phrase: "", sentence: ""),
    Junior_High_School_Word(id: 37, english: "feeling", chinese: "感覺", phrase: "", sentence: ""),
    Junior_High_School_Word(id: 38, english: "frighten", chinese: "使嚇到", phrase: "fright", sentence: "驚嚇"),
    Junior_High_School_Word(id: 39, english: "interest", chinese: "使…感興趣\\興趣", phrase: "", sentence: ""),
    Junior_High_School_Word(id: 40, english: "jealous", chinese: "忌妒的", phrase: "", sentence: "envious是羨慕別人的好"),
    Junior_High_School_Word(id: 41, english: "nervous", chinese: "緊張的", phrase: "", sentence: ""),
    Junior_High_School_Word(id: 42, english: "patience", chinese: "耐心", phrase: "", sentence: ""),
    Junior_High_School_Word(id: 43, english: "patient", chinese: "有耐心的\\病人", phrase: "", sentence: ""),
    Junior_High_School_Word(id: 44, english: "pity", chinese: "憐憫\\可惜", phrase: "", sentence: ""),
    Junior_High_School_Word(id: 45, english: "pleased", chinese: "滿意的", phrase: "", sentence: ""),
    Junior_High_School_Word(id: 46, english: "please", chinese: "取悅", phrase: "", sentence: ""),
    Junior_High_School_Word(id: 47, english: "pleasure", chinese: "樂趣", phrase: "", sentence: ""),
    Junior_High_School_Word(id: 48, english: "pride", chinese: "驕傲", phrase: "", sentence: ""),
    Junior_High_School_Word(id: 49, english: "proud", chinese: "自豪的", phrase: "to be proud of", sentence: "為…而驕傲"),
    Junior_High_School_Word(id: 50, english: "relax", chinese: "放鬆", phrase: "relaxed", sentence: "放鬆的"),
];

List<Junior_High_School_Word> unit6 = [
    Junior_High_School_Word(id: 1, english: "baby", chinese: "嬰兒", phrase: "", sentence: ""),
    Junior_High_School_Word(id: 2, english: "boy", chinese: "男孩", phrase: "", sentence: ""),
    Junior_High_School_Word(id: 3, english: "child", chinese: "小孩", phrase: "", sentence: ""),
    Junior_High_School_Word(id: 4, english: "ghost", chinese: "鬼", phrase: "", sentence: ""),
    Junior_High_School_Word(id: 5, english: "giant", chinese: "巨人", phrase: "", sentence: ""),
    Junior_High_School_Word(id: 6, english: "girl", chinese: "女孩", phrase: "", sentence: ""),
    Junior_High_School_Word(id: 7, english: "guy", chinese: "傢伙", phrase: "", sentence: ""),
    Junior_High_School_Word(id: 8, english: "kid", chinese: "小孩\\開玩笑", phrase: "", sentence: ""),
    Junior_High_School_Word(id: 9, english: "king", chinese: "國王", phrase: "", sentence: ""),
    Junior_High_School_Word(id: 10, english: "leader", chinese: "領導人", phrase: "", sentence: ""),
    Junior_High_School_Word(id: 11, english: "man", chinese: "男人", phrase: "", sentence: ""),
    Junior_High_School_Word(id: 12, english: "Miss", chinese: "小姐", phrase: "", sentence: ""),
    Junior_High_School_Word(id: 13, english: "Mr.", chinese: "先生", phrase: "", sentence: ""),
    Junior_High_School_Word(id: 14, english: "Mrs.", chinese: "太太", phrase: "", sentence: ""),
    Junior_High_School_Word(id: 15, english: "Ms.", chinese: "女士", phrase: "", sentence: ""),
    Junior_High_School_Word(id: 16, english: "name", chinese: "名字\\取名", phrase: "", sentence: ""),
    Junior_High_School_Word(id: 17, english: "neighbor", chinese: "鄰居", phrase: "", sentence: ""),
    Junior_High_School_Word(id: 18, english: "people", chinese: "人們", phrase: "", sentence: ""),
    Junior_High_School_Word(id: 19, english: "person", chinese: "人們", phrase: "", sentence: ""),
    Junior_High_School_Word(id: 20, english: "prince", chinese: "王子", phrase: "", sentence: ""),
    Junior_High_School_Word(id: 21, english: "princess", chinese: "公主", phrase: "", sentence: ""),
    Junior_High_School_Word(id: 22, english: "queen", chinese: "皇后", phrase: "", sentence: ""),
    Junior_High_School_Word(id: 23, english: "sir", chinese: "先生", phrase: "", sentence: ""),
    Junior_High_School_Word(id: 24, english: "stranger", chinese: "陌生人", phrase: "", sentence: ""),
    Junior_High_School_Word(id: 25, english: "teenager", chinese: "青少年", phrase: "", sentence: ""),
    Junior_High_School_Word(id: 26, english: "woman", chinese: "女人", phrase: "", sentence: ""),
    Junior_High_School_Word(id: 27, english: "adult", chinese: "成人", phrase: "", sentence: ""),
    Junior_High_School_Word(id: 28, english: "angle", chinese: "天使", phrase: "", sentence: ""),
    Junior_High_School_Word(id: 29, english: "audience", chinese: "聽眾", phrase: "", sentence: ""),
    Junior_High_School_Word(id: 30, english: "beauty", chinese: "美女", phrase: "", sentence: ""),
    Junior_High_School_Word(id: 31, english: "childhood", chinese: "孩童時期", phrase: "", sentence: ""),
    Junior_High_School_Word(id: 32, english: "citizen", chinese: "公民", phrase: "", sentence: ""),
    Junior_High_School_Word(id: 33, english: "Confucius", chinese: "孔子", phrase: "", sentence: ""),
    Junior_High_School_Word(id: 34, english: "couple", chinese: "情侶\\數個", phrase: "", sentence: ""),
    Junior_High_School_Word(id: 35, english: "creator", chinese: "創作者", phrase: "", sentence: ""),
    Junior_High_School_Word(id: 36, english: "customer", chinese: "顧客", phrase: "", sentence: ""),
    Junior_High_School_Word(id: 37, english: "Dr.", chinese: "博士\\醫生", phrase: "", sentence: ""),
    Junior_High_School_Word(id: 38, english: "enemy", chinese: "敵人", phrase: "", sentence: ""),
    Junior_High_School_Word(id: 39, english: "fellow", chinese: "夥伴", phrase: "", sentence: ""),
    Junior_High_School_Word(id: 40, english: "follower", chinese: "追隨者", phrase: "", sentence: ""),
    Junior_High_School_Word(id: 41, english: "foreigner", chinese: "外國人", phrase: "", sentence: ""),
    Junior_High_School_Word(id: 42, english: "fool", chinese: "傻瓜", phrase: "", sentence: ""),
    Junior_High_School_Word(id: 43, english: "genius", chinese: "天才", phrase: "", sentence: ""),
    Junior_High_School_Word(id: 44, english: "gentleman", chinese: "紳士", phrase: "", sentence: ""),
    Junior_High_School_Word(id: 45, english: "God", chinese: "上帝", phrase: "", sentence: "God bless me."),
    Junior_High_School_Word(id: 46, english: "goddess", chinese: "女神", phrase: "", sentence: ""),
    Junior_High_School_Word(id: 47, english: "guest", chinese: "客人", phrase: "", sentence: ""),
    Junior_High_School_Word(id: 48, english: "hero", chinese: "英雄\\男主角", phrase: "", sentence: ""),
    Junior_High_School_Word(id: 49, english: "host", chinese: "主人", phrase: "", sentence: ""),
    Junior_High_School_Word(id: 50, english: "human", chinese: "人類\\人類的", phrase: "", sentence: ""),
    Junior_High_School_Word(id: 51, english: "lady", chinese: "女士", phrase: "", sentence: ""),
    Junior_High_School_Word(id: 52, english: "leadership", chinese: "領導", phrase: "", sentence: ""),
    Junior_High_School_Word(id: 53, english: "loser", chinese: "輸家", phrase: "", sentence: ""),
    Junior_High_School_Word(id: 54, english: "lover", chinese: "情人\\愛好者", phrase: "", sentence: ""),
    Junior_High_School_Word(id: 55, english: "madam", chinese: "夫人", phrase: "", sentence: ""),
    Junior_High_School_Word(id: 56, english: "male", chinese: "男性的", phrase: "female女性的", sentence: ""),
    Junior_High_School_Word(id: 57, english: "master", chinese: "大師\\碩士", phrase: "", sentence: ""),
    Junior_High_School_Word(id: 58, english: "partner", chinese: "夥伴", phrase: "", sentence: ""),
    Junior_High_School_Word(id: 59, english: "passenger", chinese: "乘客\\行人", phrase: "", sentence: ""),
    Junior_High_School_Word(id: 60, english: "patient", chinese: "病人\\有耐心的", phrase: "", sentence: ""),
    Junior_High_School_Word(id: 61, english: "prisoner", chinese: "囚犯", phrase: "", sentence: ""),
    Junior_High_School_Word(id: 62, english: "robot", chinese: "機器人", phrase: "", sentence: ""),
    Junior_High_School_Word(id: 63, english: "speaker", chinese: "講者\\喇叭", phrase: "", sentence: ""),
    Junior_High_School_Word(id: 64, english: "thief", chinese: "小偷", phrase: "", sentence: ""),
    Junior_High_School_Word(id: 65, english: "user", chinese: "使用者", phrase: "", sentence: ""),
    Junior_High_School_Word(id: 66, english: "visitor", chinese: "參觀者\\遊客", phrase: "", sentence: ""),
    Junior_High_School_Word(id: 67, english: "voter", chinese: "投票者", phrase: "", sentence: ""),
    Junior_High_School_Word(id: 68, english: "winner", chinese: "贏家", phrase: "", sentence: ""),
    Junior_High_School_Word(id: 69, english: "youth", chinese: "青年", phrase: "", sentence: ""),
];

List<Junior_High_School_Word> unit7 = [
    Junior_High_School_Word(id: 1, english: "beautiful", chinese: "美麗的", phrase: "", sentence: ""),
    Junior_High_School_Word(id: 2, english: "blind", chinese: "盲的", phrase: "to turn a blind eye to sth", sentence: "對…視若無睹"),
    Junior_High_School_Word(id: 3, english: "cute", chinese: "可愛的", phrase: "", sentence: ""),
    Junior_High_School_Word(id: 4, english: "fat", chinese: "肥胖的", phrase: "", sentence: ""),
    Junior_High_School_Word(id: 5, english: "handsome", chinese: "帥的", phrase: "", sentence: ""),
    Junior_High_School_Word(id: 6, english: "heavy", chinese: "重的", phrase: "a heavy smoker/drinker", sentence: "老煙槍/酒鬼"),
    Junior_High_School_Word(id: 7, english: "old", chinese: "老的", phrase: "", sentence: ""),
    Junior_High_School_Word(id: 8, english: "pretty", chinese: "漂亮的/非常", phrase: "", sentence: ""),
    Junior_High_School_Word(id: 9, english: "short", chinese: "短的/矮的", phrase: "a short cut; be a short of", sentence: "捷徑; 短缺"),
    Junior_High_School_Word(id: 10, english: "slim", chinese: "苗條的", phrase: "", sentence: ""),
    Junior_High_School_Word(id: 11, english: "tall", chinese: "高的", phrase: "", sentence: ""),
    Junior_High_School_Word(id: 12, english: "thin", chinese: "瘦的/薄的", phrase: "", sentence: ""),
    Junior_High_School_Word(id: 13, english: "young", chinese: "年輕的", phrase: "", sentence: ""),
    Junior_High_School_Word(id: 14, english: "appearance", chinese: "外表", phrase: "", sentence: ""),
    Junior_High_School_Word(id: 15, english: "chubby", chinese: "圓胖的", phrase: "", sentence: ""),
    Junior_High_School_Word(id: 16, english: "deaf", chinese: "聾的", phrase: "to turn a deaf ear to sth", sentence: "對…充耳不聞"),
    Junior_High_School_Word(id: 17, english: "dumb", chinese: "啞的/無聲的", phrase: "", sentence: ""),
    Junior_High_School_Word(id: 18, english: "fashionable", chinese: "時髦的", phrase: "", sentence: ""),
    Junior_High_School_Word(id: 19, english: "figure", chinese: "身材", phrase: "", sentence: ""),
    Junior_High_School_Word(id: 20, english: "fit", chinese: "勻稱的/適合", phrase: "fitness center; gym", sentence: "健身中心; 健身房"),
    Junior_High_School_Word(id: 21, english: "haircut", chinese: "理髮", phrase: "", sentence: ""),
    Junior_High_School_Word(id: 22, english: "nice-looking", chinese: "好看的", phrase: "", sentence: ""),
    Junior_High_School_Word(id: 23, english: "over-weight", chinese: "過重的", phrase: "", sentence: ""),
    Junior_High_School_Word(id: 24, english: "skinny", chinese: "皮包骨的", phrase: "", sentence: ""),
    Junior_High_School_Word(id: 25, english: "slender", chinese: "纖瘦的", phrase: "", sentence: ""),
    Junior_High_School_Word(id: 26, english: "ugly", chinese: "醜的", phrase: "", sentence: ""),
    Junior_High_School_Word(id: 27, english: "under-weight", chinese: "體重過輕的", phrase: "", sentence: ""), // 請注意, 正確的翻譯可能是"體重過輕的"而非您給出的"體重過重的"
    Junior_High_School_Word(id: 28, english: "youthful", chinese: "年輕的", phrase: "", sentence: "")
];


List<Junior_High_School_Word> unit8 = [
    Junior_High_School_Word(id: 1, english: "bad", chinese: "壞的", phrase: "", sentence: ""),
    Junior_High_School_Word(id: 2, english: "bright", chinese: "聰明的", phrase: "", sentence: ""),
    Junior_High_School_Word(id: 3, english: "careful", chinese: "謹慎的", phrase: "", sentence: ""),
    Junior_High_School_Word(id: 4, english: "cool", chinese: "酷的\\冷淡的", phrase: "", sentence: ""),
    Junior_High_School_Word(id: 5, english: "dirty", chinese: "髒兮兮的\\卑劣的", phrase: "", sentence: ""),
    Junior_High_School_Word(id: 6, english: "excellent", chinese: "優秀的", phrase: "", sentence: ""),
    Junior_High_School_Word(id: 7, english: "famous", chinese: "知名的", phrase: "", sentence: ""),
    Junior_High_School_Word(id: 8, english: "friendly", chinese: "友善的", phrase: "", sentence: ""),
    Junior_High_School_Word(id: 9, english: "funny", chinese: "滑稽的", phrase: "", sentence: ""),
    Junior_High_School_Word(id: 10, english: "good", chinese: "好的", phrase: "goods", sentence: "商品"),
    Junior_High_School_Word(id: 11, english: "great", chinese: "很棒的", phrase: "", sentence: ""),
    Junior_High_School_Word(id: 12, english: "hand-working", chinese: "認真工作的", phrase: "", sentence: ""),
    Junior_High_School_Word(id: 13, english: "honest", chinese: "誠實的", phrase: "", sentence: ""),
    Junior_High_School_Word(id: 14, english: "kind", chinese: "仁慈的\\種類", phrase: "", sentence: ""),
    Junior_High_School_Word(id: 15, english: "lazy", chinese: "懶惰的", phrase: "", sentence: ""),
    Junior_High_School_Word(id: 16, english: "lovely", chinese: "可愛的", phrase: "", sentence: ""),
    Junior_High_School_Word(id: 17, english: "mean", chinese: "苛刻的\\壞脾氣的", phrase: "", sentence: ""),
    Junior_High_School_Word(id: 18, english: "nice", chinese: "好心的", phrase: "", sentence: ""),
    Junior_High_School_Word(id: 19, english: "polite", chinese: "有禮貌的", phrase: "", sentence: ""),
    Junior_High_School_Word(id: 20, english: "poor", chinese: "窮困的", phrase: "", sentence: ""),
    Junior_High_School_Word(id: 21, english: "popular", chinese: "受歡迎的", phrase: "", sentence: ""),
    Junior_High_School_Word(id: 22, english: "proud", chinese: "驕傲的", phrase: "", sentence: ""),
    Junior_High_School_Word(id: 23, english: "quiet", chinese: "安靜的", phrase: "", sentence: ""),
    Junior_High_School_Word(id: 24, english: "rich", chinese: "富裕的", phrase: "", sentence: ""),
    Junior_High_School_Word(id: 25, english: "serious", chinese: "嚴肅的\\認真的", phrase: "", sentence: ""),
    Junior_High_School_Word(id: 26, english: "shy", chinese: "害羞的", phrase: "", sentence: ""),
    Junior_High_School_Word(id: 27, english: "smart", chinese: "聰明的", phrase: "", sentence: ""),
    Junior_High_School_Word(id: 28, english: "special", chinese: "特別的", phrase: "", sentence: ""),
    Junior_High_School_Word(id: 29, english: "strange", chinese: "奇怪\\陌生的", phrase: "strander", sentence: "陌生人"),
    Junior_High_School_Word(id: 30, english: "stupid", chinese: "愚笨的", phrase: "", sentence: ""),
    Junior_High_School_Word(id: 31, english: "successful", chinese: "成功的", phrase: "", sentence: ""),
    Junior_High_School_Word(id: 32, english: "wise", chinese: "明智的", phrase: "", sentence: ""),
    Junior_High_School_Word(id: 33, english: "active", chinese: "有活力的", phrase: "", sentence: ""),
    Junior_High_School_Word(id: 34, english: "brave", chinese: "勇敢的", phrase: "", sentence: ""),
    Junior_High_School_Word(id: 35, english: "careless", chinese: "粗心的\\不在意的", phrase: "", sentence: ""),
    Junior_High_School_Word(id: 36, english: "childish", chinese: "幼稚的", phrase: "", sentence: ""),
    Junior_High_School_Word(id: 37, english: "clever", chinese: "聰明的", phrase: "", sentence: ""),
    Junior_High_School_Word(id: 38, english: "confident", chinese: "有自信的", phrase: "confidence", sentence: "信心"),
    Junior_High_School_Word(id: 39, english: "considerate", chinese: "體貼的", phrase: "", sentence: ""),
    Junior_High_School_Word(id: 40, english: "courage", chinese: "勇氣", phrase: "", sentence: ""),
    Junior_High_School_Word(id: 41, english: "decisive", chinese: "果斷的", phrase: "", sentence: ""),
    Junior_High_School_Word(id: 42, english: "dependent", chinese: "依賴的", phrase: "be dependent on", sentence: "依賴…"),
    Junior_High_School_Word(id: 43, english: "diligent", chinese: "勤奮的", phrase: "", sentence: ""),
    Junior_High_School_Word(id: 44, english: "dishonest", chinese: "不誠實的", phrase: "", sentence: ""),
    Junior_High_School_Word(id: 45, english: "dutiful", chinese: "順從的\\守本分的", phrase: "", sentence: ""),
    Junior_High_School_Word(id: 46, english: "energetic", chinese: "精力充沛的", phrase: "", sentence: ""),
    Junior_High_School_Word(id: 47, english: "evil", chinese: "邪惡的", phrase: "", sentence: ""),
    Junior_High_School_Word(id: 48, english: "expressive", chinese: "更具表現力的", phrase: "", sentence: ""),
    Junior_High_School_Word(id: 49, english: "foolish", chinese: "愚笨的", phrase: "", sentence: ""),
    Junior_High_School_Word(id: 50, english: "frank", chinese: "坦白的", phrase: "", sentence: ""),
    Junior_High_School_Word(id: 51, english: "generous", chinese: "慷慨的", phrase: "", sentence: ""),
    Junior_High_School_Word(id: 52, english: "gentle", chinese: "溫柔的", phrase: "", sentence: ""),
    Junior_High_School_Word(id: 53, english: "greedy", chinese: "貪心的", phrase: "", sentence: ""),
    Junior_High_School_Word(id: 54, english: "heroic", chinese: "英勇的", phrase: "", sentence: ""),
    Junior_High_School_Word(id: 55, english: "honesty", chinese: "誠實的", phrase: "", sentence: ""),
    Junior_High_School_Word(id: 56, english: "humble", chinese: "謙虛的", phrase: "", sentence: ""),
    Junior_High_School_Word(id: 57, english: "humor", chinese: "幽默", phrase: "", sentence: ""),
    Junior_High_School_Word(id: 58, english: "childlike", chinese: "天真無邪的", phrase: "", sentence: ""),
    Junior_High_School_Word(id: 59, english: "humorous", chinese: "幽默的", phrase: "", sentence: ""),
    Junior_High_School_Word(id: 60, english: "ignorant", chinese: "無知\\愚昧的", phrase: "", sentence: ""),
    Junior_High_School_Word(id: 61, english: "imaginative", chinese: "富有想像力的", phrase: "", sentence: ""),
    Junior_High_School_Word(id: 62, english: "independent", chinese: "獨立的", phrase: "independence", sentence: "獨立\\自主"),
    Junior_High_School_Word(id: 63, english: "innocent", chinese: "無辜\\天真的", phrase: "", sentence: ""),
    Junior_High_School_Word(id: 64, english: "intelligent", chinese: "聰明的", phrase: "intelligence", sentence: "智慧\\才智"),
    Junior_High_School_Word(id: 65, english: "joyful", chinese: "愉快的", phrase: "", sentence: ""),
    Junior_High_School_Word(id: 66, english: "justice", chinese: "公正\\正義", phrase: "", sentence: ""),
    Junior_High_School_Word(id: 67, english: "kindness", chinese: "仁慈\\親切", phrase: "", sentence: ""),
    Junior_High_School_Word(id: 68, english: "knowledge", chinese: "知識", phrase: "", sentence: ""),
    Junior_High_School_Word(id: 69, english: "loyal", chinese: "忠誠的", phrase: "loyalty", sentence: "忠誠"),
    Junior_High_School_Word(id: 70, english: "lucky", chinese: "幸運的", phrase: "", sentence: ""),
    Junior_High_School_Word(id: 71, english: "mature", chinese: "成熟的", phrase: "", sentence: ""),
    Junior_High_School_Word(id: 72, english: "modest", chinese: "謙虛的", phrase: "", sentence: ""),
    Junior_High_School_Word(id: 73, english: "naughty", chinese: "淘氣的", phrase: "", sentence: ""),
    Junior_High_School_Word(id: 74, english: "optimistic", chinese: "樂觀的", phrase: "", sentence: ""),
    Junior_High_School_Word(id: 75, english: "outgoing", chinese: "外向的", phrase: "", sentence: ""),
    Junior_High_School_Word(id: 76, english: "passion", chinese: "熱情\\激情", phrase: "", sentence: ""),
    Junior_High_School_Word(id: 77, english: "patience", chinese: "耐心", phrase: "be patient with", sentence: "對…有耐心"),
    Junior_High_School_Word(id: 78, english: "peace", chinese: "和平", phrase: "", sentence: ""),
    Junior_High_School_Word(id: 79, english: "pessimistic", chinese: "悲觀的", phrase: "", sentence: ""),
    Junior_High_School_Word(id: 80, english: "rational", chinese: "理智的", phrase: "", sentence: ""),
    Junior_High_School_Word(id: 81, english: "respect", chinese: "尊重", phrase: "", sentence: ""),
    Junior_High_School_Word(id: 82, english: "responsible", chinese: "有責任的", phrase: "take responsibility for", sentence: "對…承擔責任"),
    Junior_High_School_Word(id: 83, english: "romantic", chinese: "浪漫的", phrase: "", sentence: ""),
    Junior_High_School_Word(id: 84, english: "sensible", chinese: "明智的", phrase: "", sentence: ""),
    Junior_High_School_Word(id: 85, english: "sensitive", chinese: "敏感的", phrase: "", sentence: ""),
    Junior_High_School_Word(id: 86, english: "stubborn", chinese: "固執的", phrase: "", sentence: ""),
    Junior_High_School_Word(id: 87, english: "sympathy", chinese: "同情\\同感", phrase: "have sympathy for", sentence: "對…表示同情"),
    Junior_High_School_Word(id: 88, english: "talent", chinese: "才能\\天資", phrase: "", sentence: ""),
    Junior_High_School_Word(id: 89, english: "thoughtful", chinese: "體貼的", phrase: "", sentence: ""),
    Junior_High_School_Word(id: 90, english: "trust", chinese: "信任\\信賴", phrase: "put trust in", sentence: "信任"),
    Junior_High_School_Word(id: 91, english: "truth", chinese: "真實\\真相", phrase: "", sentence: ""),
    Junior_High_School_Word(id: 92, english: "understanding", chinese: "了解\\諒解", phrase: "", sentence: ""),
    Junior_High_School_Word(id: 93, english: "unselfish", chinese: "不自私的", phrase: "", sentence: ""),
    Junior_High_School_Word(id: 94, english: "upset", chinese: "不高興的\\沮喪的", phrase: "", sentence: ""),
    Junior_High_School_Word(id: 95, english: "warm-hearted", chinese: "熱心的", phrase: "", sentence: ""),
    Junior_High_School_Word(id: 96, english: "wise", chinese: "明智的", phrase: "", sentence: ""),
    Junior_High_School_Word(id: 97, english: "witty", chinese: "機智的", phrase: "", sentence: ""),
    Junior_High_School_Word(id: 98, english: "bravery", chinese: "勇敢", phrase: "", sentence: ""),
    Junior_High_School_Word(id: 99, english: "courageous", chinese: "有勇氣的", phrase: "", sentence: ""),
    Junior_High_School_Word(id: 100, english: "coward", chinese: "懦夫", phrase: "", sentence: ""),
    Junior_High_School_Word(id: 101, english: "cowardly", chinese: "懦弱的", phrase: "", sentence: ""),
    Junior_High_School_Word(id: 102, english: "daring", chinese: "大膽的", phrase: "", sentence: ""),
    Junior_High_School_Word(id: 103, english: "fearful", chinese: "害怕的", phrase: "", sentence: ""),
    Junior_High_School_Word(id: 104, english: "fearless", chinese: "無畏的", phrase: "", sentence: ""),
    Junior_High_School_Word(id: 105, english: "hero", chinese: "英雄", phrase: "", sentence: ""),
    Junior_High_School_Word(id: 106, english: "heroine", chinese: "女英雄", phrase: "", sentence: ""),
    Junior_High_School_Word(id: 107, english: "valiant", chinese: "英勇的", phrase: "", sentence: ""),
    Junior_High_School_Word(id: 108, english: "valor", chinese: "英勇", phrase: "", sentence: ""),
    Junior_High_School_Word(id: 109, english: "venture", chinese: "冒險", phrase: "", sentence: ""),
    Junior_High_School_Word(id: 110, english: "wimp", chinese: "懦夫", phrase: "", sentence: ""),
    Junior_High_School_Word(id: 111, english: "yield", chinese: "放棄\\讓步", phrase: "", sentence: ""),
    Junior_High_School_Word(id: 112, english: "bold", chinese: "大膽的", phrase: "", sentence: ""),
    Junior_High_School_Word(id: 113, english: "bravado", chinese: "虛張聲勢", phrase: "", sentence: ""),
    Junior_High_School_Word(id: 114, english: "dauntless", chinese: "不屈不撓的", phrase: "", sentence: ""),
    Junior_High_School_Word(id: 115, english: "intrepid", chinese: "無畏的", phrase: "", sentence: ""),
    Junior_High_School_Word(id: 116, english: "meek", chinese: "溫順的", phrase: "", sentence: ""),
    Junior_High_School_Word(id: 117, english: "timid", chinese: "膽小的", phrase: "", sentence: ""),
    Junior_High_School_Word(id: 118, english: "undaunted", chinese: "不畏懼的", phrase: "", sentence: ""),
    Junior_High_School_Word(id: 119, english: "apprehensive", chinese: "擔心的", phrase: "", sentence: ""),
    Junior_High_School_Word(id: 120, english: "dread", chinese: "恐懼", phrase: "", sentence: "")
];

