/*
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see <http://www.gnu.org/licenses/>.
 *
 * Author: Nelson Chung
 * Creation Date: September 3, 2023
 */
 
class Phrase {
	final int id;
	final String english;
	final String chinese;

	Phrase({required this.id, required this.english, required this.chinese});
}

List<Phrase> phrases = [
	Phrase(id: 1, english: "about to", chinese: "即將"),
	Phrase(id: 2, english: "according to", chinese: "根據"),
	Phrase(id: 3, english: "a couple of", chinese: "一對...好幾唱..."),
	Phrase(id: 4, english: "after all", chinese: "畢竟"),
	Phrase(id: 5, english: "a lot of = lots of", chinese: "很多"),
	Phrase(id: 6, english: "along with", chinese: "和...一起"),
	Phrase(id: 7, english: "all day long", chinese: "一整天"),
	Phrase(id: 8, english: "all kinds of", chinese: "各式各樣的"),
	Phrase(id: 9, english: "all night long", chinese: "整夜"),
	Phrase(id: 10, english: "all of a sudden", chinese: "突然間"),
	Phrase(id: 11, english: "all right", chinese: "好"),
	Phrase(id: 12, english: "all the time = always", chinese: "總是"),
	Phrase(id: 13, english: "argue with sb", chinese: "與人爭論"),
	Phrase(id: 14, english: "arrive in/at+地方", chinese: "抵..."),
	Phrase(id: 15, english: "ask for sth", chinese: "要求...東西"),
	Phrase(id: 16, english: "as a matter of fact", chinese: "事實上"),
	Phrase(id: 17, english: "as for", chinese: "至於...關於..."),
	Phrase(id: 18, english: "as long as", chinese: "只要"),
	Phrase(id: 19, english: "as soon as", chinese: "一⋯就.."),
	Phrase(id: 20, english: "as usual", chinese: "一如往常"),
	Phrase(id: 21, english: "as well as = and", chinese: "和"),
	Phrase(id: 22, english: "at first", chinese: "首先"),
	Phrase(id: 23, english: "at last", chinese: "最後"),
	Phrase(id: 24, english: "at least", chinese: "至少"),
	Phrase(id: 25, english: "at most", chinese: "最多"),
	Phrase(id: 26, english: "at once = right away", chinese: "立刻"),
	Phrase(id: 27, english: "back up = support", chinese: "支持"),
	Phrase(id: 28, english: "be able to", chinese: "能夠"),
	Phrase(id: 29, english: "be afraid of+N", chinese: "害怕..."),
	Phrase(id: 30, english: "be angry with sb", chinese: "對某人生氣"),
	Phrase(id: 31, english: "be aware of", chinese: "注意/意識到"),
	Phrase(id: 32, english: "be based on", chinese: "根據"),
	Phrase(id: 33, english: "be bored with", chinese: "對...感到無趣"),
	Phrase(id: 34, english: "be busy + V-ing", chinese: "忙..."),
	Phrase(id: 35, english: "be concerned about", chinese: "擔心"),
	Phrase(id: 36, english: "be covered with", chinese: "覆蓋"),
	Phrase(id: 37, english: "be crazy about", chinese: "瘋狂喜愛.."),
	Phrase(id: 38, english: "be different from", chinese: "與...不同"),
	Phrase(id: 39, english: "be dressed in", chinese: "穿著"),
	Phrase(id: 40, english: "be eager to+V", chinese: "渴望做..."),
	Phrase(id: 41, english: "be familiar with", chinese: "熟悉"),
	Phrase(id: 42, english: "be famous for", chinese: "以...著名"),
	Phrase(id: 43, english: "be full of a be filled with", chinese: "充滿"),
	Phrase(id: 44, english: "be good at", chinese: "擅長於"),
	Phrase(id: 45, english: "be good for", chinese: "對...有益"),
	Phrase(id: 46, english: "be harmful to", chinese: "對...有害"),
	Phrase(id: 47, english: "be in danger", chinese: "處於危險中"),
	Phrase(id: 48, english: "be known for", chinese: "以...著名"),
	Phrase(id: 49, english: "be likely to", chinese: "可能會..."),
	Phrase(id: 50, english: "be made of", chinese: "由...組成"),
	Phrase(id: 51, english: "be proud of", chinese: "為...感到驕傲"),
	Phrase(id: 52, english: "be ready to", chinese: "準備做某事"),
	Phrase(id: 53, english: "be satisfied with", chinese: "對...滿意"),
	Phrase(id: 54, english: "be sick of", chinese: "感到厭煩"),
	Phrase(id: 55, english: "be sorry for", chinese: "對...感到抱歉"),
	Phrase(id: 56, english: "be sure to", chinese: "務必"),
	Phrase(id: 57, english: "be tired of", chinese: "感到厭煩"),
	Phrase(id: 58, english: "be used to + V-ing", chinese: "習慣於"),
	Phrase(id: 59, english: "be willing to", chinese: "願意"),
	Phrase(id: 60, english: "be worried about", chinese: "擔心"),
	Phrase(id: 61, english: "be worth + V-ing", chinese: "值得..."),
	Phrase(id: 62, english: "belong to sb", chinese: "屬於某人"),
	Phrase(id: 63, english: "believe in", chinese: "相信"),
	Phrase(id: 64, english: "benefit from", chinese: "受益於"),
	Phrase(id: 65, english: "beware of", chinese: "當心"),
	Phrase(id: 66, english: "break in", chinese: "闖入"),
	Phrase(id: 67, english: "bring up sb", chinese: "扶養某人長大"),
	Phrase(id: 68, english: "burst out + V-ing", chinese: "突然...起來"),
	Phrase(id: 69, english: "by all means", chinese: "務必/絕對"),
	Phrase(id: 70, english: "by means of", chinese: "由/透過"),
	Phrase(id: 71, english: "by oneself", chinese: "獨自/靠自己"),
	Phrase(id: 72, english: "by the way", chinese: "順帶一提"),
	Phrase(id: 73, english: "call it a day", chinese: "結束當天的工作"),
	Phrase(id: 74, english: "call off", chinese: "取消"),
	Phrase(id: 75, english: "call sb down", chinese: "責備某人"),
	Phrase(id: 76, english: "call up sb", chinese: "打電話給某人"),
	Phrase(id: 77, english: "can't help + Ving", chinese: "忍不住"),
	Phrase(id: 78, english: "carry out", chinese: "實行/完成"),
	Phrase(id: 79, english: "catch (a bad) cold", chinese: "感冒"),
	Phrase(id: 80, english: "catch fire", chinese: "著火"),
	Phrase(id: 81, english: "check in", chinese: "飯店入住登記或班機登機確認"),
	Phrase(id: 82, english: "check out", chinese: "飯店退房"),
	Phrase(id: 83, english: "cheer up", chinese: "加油打氣"),
	Phrase(id: 84, english: "come back", chinese: "回來/返回"),
	Phrase(id: 85, english: "come from", chinese: "來自⋯."),
	Phrase(id: 86, english: "come true", chinese: "夢想實現"),
	Phrase(id: 87, english: "come up with", chinese: "想出..."),
	Phrase(id: 88, english: "complain about", chinese: "抱怨"),
	Phrase(id: 89, english: "cool down", chinese: "降溫/平靜"),
	Phrase(id: 90, english: "count on", chinese: "依賴/依靠"),
	Phrase(id: 91, english: "cover up", chinese: "掩飾/掩蓋"),
	Phrase(id: 92, english: "day after day", chinese: "日復一日"),
	Phrase(id: 93, english: "day off", chinese: "放假"),
	Phrase(id: 94, english: "deal in", chinese: "...交易/經營"),
	Phrase(id: 95, english: "deal with = handle", chinese: "處理"),
	Phrase(id: 96, english: "die from", chinese: "死於..."),
	Phrase(id: 97, english: "do one's best", chinese: "盡全力"),
	Phrase(id: 98, english: "dozens of...", chinese: "數打/數十個"),
	Phrase(id: 99, english: "dress up", chinese: "盛裝打扮"),
	Phrase(id: 100, english: "drop off", chinese: "降低"),
	Phrase(id: 101, english: "earn one's living", chinese: "賺取生計"),
	Phrase(id: 102, english: "eat in", chinese: "在家用餐"),
	Phrase(id: 103, english: "eat out", chinese: "外食"),
	Phrase(id: 104, english: "end up + V-ing", chinese: "結束..."),
	Phrase(id: 105, english: "enjoy oneself", chinese: "玩得開心"),
	Phrase(id: 106, english: "even if-even though", chinese: "雖然"),
	Phrase(id: 107, english: "every now and then", chinese: "偶爾"),
	Phrase(id: 108, english: "every other day", chinese: "每隔一天"),
	Phrase(id: 109, english: "fall apart", chinese: "破碎成片/散架"),
	Phrase(id: 110, english: "fall asleep", chinese: "睡著"),
	Phrase(id: 111, english: "fall behind", chinese: "落後/趕不上"),
	Phrase(id: 112, english: "fall in love", chinese: "與某人戀愛"),
	Phrase(id: 113, english: "feel like + V-ing", chinese: "想要..."),
	Phrase(id: 114, english: "feel sorry for", chinese: "覺得可惜"),
	Phrase(id: 115, english: "figure out", chinese: "想出、/解決.."),
	Phrase(id: 116, english: "find out", chinese: "發現"),
	Phrase(id: 117, english: "fool around", chinese: "鬼混"),
	Phrase(id: 118, english: "for example", chinese: "例如"),
	Phrase(id: 119, english: "for fear of", chinese: "害怕"),
	Phrase(id: 120, english: "for free", chinese: "免費"),
	Phrase(id: 121, english: "for good = forever", chinese: "永久"),
	Phrase(id: 122, english: "for sure", chinese: "確定地"),
	Phrase(id: 123, english: "from then on", chinese: "從那時起"),
	Phrase(id: 124, english: "get along with", chinese: "與...相處得好"),
	Phrase(id: 125, english: "get in/on", chinese: "上車"),
	Phrase(id: 126, english: "get in touch with", chinese: "保持聯絡"),
	Phrase(id: 127, english: "get into trouble", chinese: "陷入麻煩"),
	Phrase(id: 128, english: "get lost", chinese: "迷路"),
	Phrase(id: 129, english: "get off", chinese: "下車(公車/火車)"),
	Phrase(id: 130, english: "get out of", chinese: "離開"),
	Phrase(id: 131, english: "get over", chinese: "克服問題"),
	Phrase(id: 132, english: "get rid of", chinese: "消除..去掉.."),
	Phrase(id: 133, english: "get out of", chinese: "下車(汽車)"),
	Phrase(id: 134, english: "get to", chinese: "到達 = arrive in/at"),
	Phrase(id: 135, english: "get up", chinese: "起床"),
	Phrase(id: 136, english: "give in", chinese: "投降/讓步"),
	Phrase(id: 137, english: "give birth to", chinese: "生孩子"),
	Phrase(id: 138, english: "give sb a hand", chinese: "幫助"),
	Phrase(id: 139, english: "give up + V-ing", chinese: "放棄/停止"),
	Phrase(id: 140, english: "go on", chinese: "繼續"),
	Phrase(id: 141, english: "go on a diet", chinese: "節食"),
	Phrase(id: 142, english: "go on a picnic", chinese: "去野餐"),
	Phrase(id: 143, english: "go through", chinese: "..."),
	Phrase(id: 144, english: "go with", chinese: "和...很搭配"),
	Phrase(id: 145, english: "grow up", chinese: "長大"),
	Phrase(id: 146, english: "had better + 原V", chinese: "最好"),
	Phrase(id: 147, english: "hand in = turn in", chinese: "繳交"),
	Phrase(id: 148, english: "hand up", chinese: "掛新電話"),
	Phrase(id: 149, english: "have a gift for", chinese: "在...有天賦"),
	Phrase(id: 150, english: "have a good time", chinese: "玩得開心"),
	Phrase(id: 151, english: "have to", chinese: "必須"),
	Phrase(id: 152, english: "happen to sb", chinese: "某事發生於某人"),
	Phrase(id: 153, english: "hear of/about", chinese: "聽說"),
	Phrase(id: 154, english: "hear from", chinese: "得到某人消息"),
	Phrase(id: 155, english: "help yourself to", chinese: "自己拿..."),
	Phrase(id: 156, english: "hold on", chinese: "稍等(電話用語)"),
	Phrase(id: 157, english: "how come = why", chinese: "為什麼"),
	Phrase(id: 158, english: "hundreds of", chinese: "數以百計"),
	Phrase(id: 159, english: "hurry up", chinese: "快一點"),
	Phrase(id: 160, english: "in a hurry", chinese: "匆忙"),
	Phrase(id: 161, english: "in a word", chinese: "總之"),
	Phrase(id: 162, english: "in addition to = besides", chinese: "除此之外"),
	Phrase(id: 163, english: "in advance", chinese: "事先"),
	Phrase(id: 164, english: "in any case", chinese: "無論如何"),
	Phrase(id: 165, english: "in case of", chinese: "萬一..."),
	Phrase(id: 166, english: "in charge of", chinese: "負責"),
	Phrase(id: 167, english: "in danger", chinese: "處於危險中"),
	Phrase(id: 168, english: "in fact", chinese: "事實上"),
	Phrase(id: 169, english: "in front of", chinese: "在前面"),
	Phrase(id: 170, english: "in back of", chinese: "在後面"),
	Phrase(id: 171, english: "in need of", chinese: "需要"),
	Phrase(id: 172, english: "in order to", chinese: "為了..."),
	Phrase(id: 173, english: "in other words", chinese: "換句話說"),
	Phrase(id: 174, english: "in person", chinese: "親自"),
	Phrase(id: 175, english: "in public", chinese: "公開"),
	Phrase(id: 176, english: "in spite of", chinese: "儘管"),
	Phrase(id: 177, english: "in the end", chinese: "最後..."),
	Phrase(id: 178, english: "in the past", chinese: "在過去"),
	Phrase(id: 179, english: "in the future", chinese: "在未來"),
	Phrase(id: 180, english: "instead of", chinese: "而不是..."),
	Phrase(id: 181, english: "keep away from", chinese: "遠離"),
	Phrase(id: 182, english: "keep an eye on", chinese: "監視..."),
	Phrase(id: 183, english: "keep away", chinese: "使遠離"),
	Phrase(id: 184, english: "keep in mind", chinese: "記在心裡"),
	Phrase(id: 185, english: "keep in shape", chinese: "保持身材"),
	Phrase(id: 186, english: "keep in touch with", chinese: "保持聯絡"),
	Phrase(id: 187, english: "keep up with", chinese: "跟上..."),
	Phrase(id: 188, english: "laugh at", chinese: "嘲笑"),
	Phrase(id: 189, english: "less and less", chinese: "越來越少"),
	Phrase(id: 190, english: "let sb down", chinese: "使某人失望"),
	Phrase(id: 191, english: "lie down", chinese: "躺下"),
	Phrase(id: 192, english: "lie in", chinese: "在於"),
	Phrase(id: 193, english: "line up", chinese: "排隊"),
	Phrase(id: 194, english: "listen to", chinese: "聆聽"),
	Phrase(id: 195, english: "look after", chinese: "照顧"),
	Phrase(id: 196, english: "look around", chinese: "四處看"),
	Phrase(id: 197, english: "look at", chinese: "注視"),
	Phrase(id: 198, english: "look down on sb", chinese: "輕視某人"),
	Phrase(id: 199, english: "look for", chinese: "尋找"),
	Phrase(id: 200, english: "look forward to", chinese: "期待"),
	Phrase(id: 201, english: "look into", chinese: "調查"),
	Phrase(id: 202, english: "look like", chinese: "看起來像"),
	Phrase(id: 203, english: "look out", chinese: "小心"),
	Phrase(id: 204, english: "look over sth", chinese: "檢查東西"),
	Phrase(id: 205, english: "look up", chinese: "查閱單字"),
	Phrase(id: 206, english: "major in", chinese: "主修...科目"),
	Phrase(id: 207, english: "make a mistake", chinese: "犯錯"),
	Phrase(id: 208, english: "make it a rule to", chinese: "養成...習慣"),
	Phrase(id: 209, english: "make fun of", chinese: "取笑..."),
	Phrase(id: 210, english: "make sure", chinese: "確定"),
	Phrase(id: 211, english: "make up", chinese: "編造故事／藉口"),
	Phrase(id: 212, english: "make use of", chinese: "利用"),
	Phrase(id: 213, english: "melt away", chinese: "融化／消失"),
	Phrase(id: 214, english: "mess up", chinese: "弄亂／弄髒"),
	Phrase(id: 215, english: "mix up", chinese: "混合"),
	Phrase(id: 216, english: "more or less", chinese: "或多或少..."),
	Phrase(id: 217, english: "name after", chinese: "以...命名"),
	Phrase(id: 218, english: "never mind", chinese: "別介意／沒關係"),
	Phrase(id: 219, english: "no doubt", chinese: "無庸置疑"),
	Phrase(id: 220, english: "no longer", chinese: "不再"),
	Phrase(id: 221, english: "not...at all", chinese: "一點也不"),
	Phrase(id: 222, english: "of one's own", chinese: "屬於自己的"),
	Phrase(id: 223, english: "on one's own", chinese: "靠自己"),
	Phrase(id: 224, english: "on earth", chinese: "究竟..."),
	Phrase(id: 225, english: "on and off", chinese: "斷斷續續"),
	Phrase(id: 226, english: "on business", chinese: "洽公"),
	Phrase(id: 227, english: "on foot", chinese: "走路"),
	Phrase(id: 228, english: "on one's own", chinese: "靠自己"),
	Phrase(id: 229, english: "on purpose", chinese: "故意地"),
	Phrase(id: 230, english: "on time", chinese: "準時"),
	Phrase(id: 231, english: "on vacation", chinese: "度假"),
	Phrase(id: 232, english: "out of date", chinese: "落伍的"),
	Phrase(id: 233, english: "out of order", chinese: "損壞／故障"),
	Phrase(id: 234, english: "out of work", chinese: "失業"),
	Phrase(id: 235, english: "pass away", chinese: "去世"),
	Phrase(id: 236, english: "pass by", chinese: "經過／路過"),
	Phrase(id: 237, english: "pass out", chinese: "暈倒"),
	Phrase(id: 238, english: "pay attention to", chinese: "專心..."),
	Phrase(id: 239, english: "pick on sb", chinese: "找某人麻煩"),
	Phrase(id: 240, english: "pick out sth", chinese: "挑選出..."),
	Phrase(id: 241, english: "pick sb up", chinese: "接送某人"),
	Phrase(id: 242, english: "pick up sth", chinese: "拾／撿起..."),
	Phrase(id: 243, english: "point at/to", chinese: "指向..."),
	Phrase(id: 244, english: "point out", chinese: "指出...事情"),
	Phrase(id: 245, english: "pray for", chinese: "為...祈禱"),
	Phrase(id: 246, english: "prepare for", chinese: "為...做準備"),
	Phrase(id: 247, english: "put away sth", chinese: "收拾整理"),
	Phrase(id: 248, english: "put off", chinese: "延期..."),
	Phrase(id: 249, english: "put on", chinese: "穿上衣物／增加"),
	Phrase(id: 250, english: "put out", chinese: "滅火"),
	Phrase(id: 251, english: "put up with", chinese: "忍受"),
	Phrase(id: 252, english: "rain cats and dogs", chinese: "傾盆大雨"),
	Phrase(id: 253, english: "rely on", chinese: "依賴／依靠"),
	Phrase(id: 254, english: "result from", chinese: "起因於"),
	Phrase(id: 255, english: "result in", chinese: "導致"),
	Phrase(id: 256, english: "right away", chinese: "馬上／立刻"),
	Phrase(id: 257, english: "right now", chinese: "目前"),
	Phrase(id: 258, english: "run after", chinese: "追趕"),
	Phrase(id: 259, english: "run into", chinese: "巧遇"),
	Phrase(id: 260, english: "run out of", chinese: "用完..."),
	Phrase(id: 261, english: "run the risk of", chinese: "冒...的風險"),
	Phrase(id: 262, english: "run over", chinese: "輾過..."),
	Phrase(id: 263, english: "scare away", chinese: "嚇跑"),
	Phrase(id: 264, english: "set out for", chinese: "出發前往"),
	Phrase(id: 265, english: "set up", chinese: "設立／設置"),
	Phrase(id: 266, english: "shake hands", chinese: "握手"),
	Phrase(id: 267, english: "show off", chinese: "炫耀"),
	Phrase(id: 268, english: "show someone around", chinese: "帶某人四處遊覽"),
	Phrase(id: 269, english: "show up", chinese: "出現"),
	Phrase(id: 270, english: "shut up", chinese: "閉嘴"),
	Phrase(id: 271, english: "so far", chinese: "到目前為止"),
	Phrase(id: 272, english: "sooner or later", chinese: "遲早..."),
	Phrase(id: 273, english: "speed up", chinese: "加速"),
	Phrase(id: 274, english: "stand by sb", chinese: "支持某人"),
	Phrase(id: 275, english: "stand for", chinese: "代表..."),
	Phrase(id: 276, english: "stare at", chinese: "注視"),
	Phrase(id: 277, english: "stay away from", chinese: "遠離"),
	Phrase(id: 278, english: "stay up", chinese: "熬夜"),
	Phrase(id: 279, english: "stop by", chinese: "順道經過"),
	Phrase(id: 280, english: "stop A from B", chinese: "防止某事發生"),
	Phrase(id: 281, english: "succeed in", chinese: "成功在...地方"),
	Phrase(id: 282, english: "suffer from", chinese: "飽受...疾病"),
	Phrase(id: 283, english: "switch off", chinese: "關掉電源"),
	Phrase(id: 284, english: "switch on", chinese: "打開電源"),
	Phrase(id: 285, english: "take a seat", chinese: "請就坐"),
	Phrase(id: 286, english: "take a nap", chinese: "小睡一下"),
	Phrase(id: 287, english: "take a break/rest", chinese: "休息一下"),
	Phrase(id: 288, english: "take a trip", chinese: "旅行"),
	Phrase(id: 289, english: "take a walk", chinese: "散步"),
	Phrase(id: 290, english: "take advantage of", chinese: "利用...方法"),
	Phrase(id: 291, english: "take off", chinese: "脫掉衣物／飛機起飛"),
	Phrase(id: 292, english: "take out", chinese: "拿出"),
	Phrase(id: 293, english: "take over N", chinese: "接管／接收"),
	Phrase(id: 294, english: "take part in", chinese: "参加"),
	Phrase(id: 295, english: "take place", chinese: "發生"),
	Phrase(id: 296, english: "take up", chinese: "佔據空間／時間"),
	Phrase(id: 297, english: "tear apart", chinese: "撕開／撕碎某物"),
	Phrase(id: 298, english: "take turns + Ving", chinese: "輪流做..."),
	Phrase(id: 299, english: "tear down", chinese: "拆掉／摧毁"),
	Phrase(id: 300, english: "tend to V", chinese: "容易於..."),
	Phrase(id: 301, english: "the other day", chinese: "前幾天"),
	Phrase(id: 302, english: "think about", chinese: "考慮／想到"),
	Phrase(id: 303, english: "throw away/out", chinese: "丟棄..."),
	Phrase(id: 304, english: "throw up", chinese: "嘔吐"),
	Phrase(id: 305, english: "to one's surprise", chinese: "令人驚訝"),
	Phrase(id: 306, english: "try on", chinese: "試穿"),
	Phrase(id: 307, english: "turn around", chinese: "轉身"),
	Phrase(id: 308, english: "turn down", chinese: "轉小聲"),
	Phrase(id: 309, english: "turn down sb", chinese: "拒絕某人"),
	Phrase(id: 310, english: "turn in", chinese: "繳交"),
	Phrase(id: 311, english: "turn into", chinese: "轉變成..."),
	Phrase(id: 312, english: "turn up", chinese: "轉大聲"),
	Phrase(id: 313, english: "turn out to", chinese: "結果是..."),
	Phrase(id: 314, english: "up to date", chinese: "最新的...東西"),
	Phrase(id: 315, english: "used to + V", chinese: "過去經常做.."),
	Phrase(id: 316, english: "wait for", chinese: "等待"),
	Phrase(id: 317, english: "wake up", chinese: "醒來"),
	Phrase(id: 318, english: "warm up", chinese: "暖身"),
	Phrase(id: 319, english: "watch out for", chinese: "小心..."),
	Phrase(id: 320, english: "wear out", chinese: "用壞掉...東西"),
	Phrase(id: 321, english: "work for", chinese: "替某人工作"),
	Phrase(id: 322, english: "work out", chinese: "解決"),
	Phrase(id: 323, english: "worry about", chinese: "擔心"),
	Phrase(id: 324, english: "with ease", chinese: "輕鬆地"),
	Phrase(id: 325, english: "year after year", chinese: "一年一年..."),
	Phrase(id: 326, english: "You bet.", chinese: "當然"),
	];


